# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ChangeAttributRoute
                                 A QGIS plugin
 Aide à la contribution directe sur le thème routier
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-01
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtWidgets import QLineEdit
# from PyQt5.uic.Compiler.qtproxies import QtGui
# from matplotlib.style import library
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication,QRegExp
from qgis.PyQt.QtGui import QRegExpValidator
from qgis.PyQt.QtWidgets import QAction,QPushButton
from qgis.utils import plugins

from copy import copy

from qgis.core import QgsExpression


from datetime import datetime
import locale
import time

from collections import namedtuple

# from scipy.signal import dlsim
# from wx.lib.pubsub.py2and3 import values
# from xlwt.ExcelFormulaLexer import false_pattern

# Import the code for the dialog
from .assistant_route_dialog import ChangeAttributRouteDialog
import os.path

from .fonction import *
from .cheminpluscourt import *
from .aproposde import Aproposde


# recuperation de l'id de la transaction (à partir du plugin espace co)
def getidtransaction():
    from qgis.utils import plugins
    idtransaction = None
    try:
        processing_plugin = plugins[PLUGIN_ESPACE_CO]
        print("espace co trouvé")
        try:
            idtransaction = processing_plugin.getlibelletransaction()
        except AttributeError:
            idtransaction = "Récuperation en cours de développement"
    except KeyError:
        print("espace co PAS trouvé")
        pass

    if idtransaction is None:
        return "Pas de transaction vers la BDUNI (travail hors ligne)"
    else:
        return idtransaction


class ChangeAttributRoute:
    """QGIS Plugin Implementation."""

    def runchepluscourt(self):
        self.cheminpluscourt.cheminpluscourt()
        self.set_activeLayerRoute()
        # zoom sur la selection
        self.iface.actionZoomToSelected().trigger()

    def torte2chaussee(self):
        if self.get_nb_selection() == 0:
            return

        self.ismodifie = True

        if self.dico_attributs_commun[NATURE] == RTE_2_CHAUSSEES:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            # self.modifie_isin_selection(RTE_2_CHAUSSEES)
            self.dlg.pushButtonRte2Chaussee.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[NATURE]
            except KeyError:
                pass
            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)

        else:
            self.dlg.pushButtonRte2Chaussee.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[NATURE] = RTE_2_CHAUSSEES
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
        self.activerBoutons(True)
        self.controleDonnees(RTE_2_CHAUSSEES)
        self.set_attributs_defaut(RTE_2_CHAUSSEES)
        self.initbtnclic(self.listbtnNature, "pushButtonRte2Chaussee")

    def torte1chaussee(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        if self.dico_attributs_commun[NATURE] == RTE_1_CHAUSSEE:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonRte1Chaussee.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[NATURE]
            except KeyError:
                pass
            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)

        else:
            self.dlg.pushButtonRte1Chaussee.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[NATURE] = RTE_1_CHAUSSEE
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)

        self.activerBoutons(True)
        self.controleDonnees(RTE_1_CHAUSSEE)
        self.set_attributs_defaut(RTE_1_CHAUSSEE)
        self.initbtnclic(self.listbtnNature, "pushButtonRte1Chaussee")



    def toempierree(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        # self.initbtnclic(self.listbtnNature, "pushButtonEmpierree")
        if self.dico_attributs_commun[NATURE] == RTE_EMPIERREE:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonEmpierree.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[NATURE]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonEmpierree.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[NATURE] = RTE_EMPIERREE
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)

        self.activerBoutons(True)
        self.controleDonnees(RTE_EMPIERREE)
        self.set_attributs_defaut(RTE_EMPIERREE)
        self.initbtnclic(self.listbtnNature, "pushButtonEmpierree")


    def tochemin(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        if self.dico_attributs_commun[NATURE] == CHEMIN:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonChemin.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[NATURE]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonChemin.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[NATURE] = CHEMIN
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)


        self.activerBoutons(True)
        self.controleDonnees(CHEMIN)
        self.set_attributs_defaut(CHEMIN)
        self.initbtnclic(self.listbtnNature, "pushButtonChemin")

    def tosentier(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        if self.dico_attributs_commun[NATURE] == SENTIER:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonSentier.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[NATURE]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonSentier.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[NATURE] = SENTIER

        self.activerBoutons(True)
        self.controleDonnees(SENTIER)
        self.set_attributs_defaut(SENTIER)
        self.initbtnclic(self.listbtnNature, "pushButtonSentier")

    def torondpoint(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        if self.dico_attributs_commun[NATURE] == ROND_POINT:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonRondpoint.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[NATURE]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonRondpoint.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[NATURE] = ROND_POINT

        self.activerBoutons(True)
        self.controleDonnees(ROND_POINT)
        self.set_attributs_defaut(ROND_POINT)
        self.initbtnclic(self.listbtnNature, "pushButtonRondpoint")

    def setvoieSansObj(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnNbVoies, "pushButtonVoieSansObjet")
        if self.dico_attributs_commun[NB_VOIES] == SANS_OBJET:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonVoieSansObjet.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[NB_VOIES]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:

            self.dlg.pushButtonVoieSansObjet.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[NB_VOIES] = SANS_OBJET



    def set1voie(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnNbVoies, "pushButton1voie")
        if self.dico_attributs_commun[NB_VOIES] == "1":
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButton1voie.setStyleSheet(CUSTOM_WIDGETS[1])

            try:
                del self.dico_attributs_modifie[NB_VOIES]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)

        else:
            self.dlg.pushButton1voie.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[NB_VOIES] = "1"



    def set2voies(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnNbVoies, "pushButton2voies")
        if self.dico_attributs_commun[NB_VOIES] == "2":
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButton2voies.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[NB_VOIES]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButton2voies.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[NB_VOIES] = "2"



    def set3voies(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnNbVoies, "pushButton3voies")
        if self.dico_attributs_commun[NB_VOIES] == "3":
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButton3voies.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[NB_VOIES]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)

        else:
            self.dlg.pushButton3voies.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[NB_VOIES] = "3"


    def setLargeur14(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnLargeur, "pushButtonLargeur14")

        # mettre en rose
        # try : gestion de la valeur "NULL" dans une clé de type nombre
        try:
            if 12.5 < self.dico_attributs_commun[LARGEUR]:
                # self.dlg.pushButtonValiderTransaction.setEnabled(False)
                # self.dlg.pushButtonActualiseSelection.setEnabled(False)
                # mettre en vert
                self.dlg.pushButtonLargeur14.setStyleSheet(CUSTOM_WIDGETS[1])

                try:
                    del self.dico_attributs_modifie[LARGEUR]
                except KeyError:
                    pass

                if len(self.dico_attributs_modifie) == 0:
                    self.dlg.pushButtonValiderTransaction.setEnabled(False)
                    self.dlg.pushButtonActualiseSelection.setEnabled(False)

            else:
                self.dlg.pushButtonLargeur14.setStyleSheet(CUSTOM_WIDGETS[0])
                self.dlg.pushButtonValiderTransaction.setEnabled(True)
                self.dlg.pushButtonActualiseSelection.setEnabled(True)
                self.dico_attributs_modifie[LARGEUR] = "14"
        except TypeError:
            self.dlg.pushButtonLargeur14.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dico_attributs_modifie[LARGEUR] = "14"
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
        self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[2])
        self.dlg.lineEditLargeur.setText("14")

    def setLargeur10(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnLargeur, "pushButtonLargeur10")

        # mettre en rose
        # try : gestion de la valeur "NULL" dans une clé de type nombre
        try:
            if 9 < self.dico_attributs_commun[LARGEUR] <= 12.5:
                # self.dlg.pushButtonValiderTransaction.setEnabled(False)
                # self.dlg.pushButtonActualiseSelection.setEnabled(False)
                # mettre en vert
                self.dlg.pushButtonLargeur10.setStyleSheet(CUSTOM_WIDGETS[1])

                try:
                    del self.dico_attributs_modifie[LARGEUR]
                except KeyError:
                    pass

                if len(self.dico_attributs_modifie) == 0:
                    self.dlg.pushButtonValiderTransaction.setEnabled(False)
                    self.dlg.pushButtonActualiseSelection.setEnabled(False)

            else:
                self.dlg.pushButtonLargeur10.setStyleSheet(CUSTOM_WIDGETS[0])
                self.dlg.pushButtonValiderTransaction.setEnabled(True)
                self.dlg.pushButtonActualiseSelection.setEnabled(True)
                self.dico_attributs_modifie[LARGEUR] = "10"
        except TypeError:
            self.dlg.pushButtonLargeur10.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dico_attributs_modifie[LARGEUR] = "10"
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
        self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[2])
        self.dlg.lineEditLargeur.setText("10")

    def setLargeur7(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnLargeur, "pushButtonLargeur7")

        # mettre en rose
        # try : gestion de la valeur "NULL" dans une clé de type nombre
        try:
            if 6.5 < self.dico_attributs_commun[LARGEUR] <= 9:
                # self.dlg.pushButtonValiderTransaction.setEnabled(False)
                # self.dlg.pushButtonActualiseSelection.setEnabled(False)
                # mettre en vert
                self.dlg.pushButtonLargeur7.setStyleSheet(CUSTOM_WIDGETS[1])

                try:
                    del self.dico_attributs_modifie[LARGEUR]
                except KeyError:
                    pass

                if len(self.dico_attributs_modifie) == 0:
                    self.dlg.pushButtonValiderTransaction.setEnabled(False)
                    self.dlg.pushButtonActualiseSelection.setEnabled(False)

            else:
                self.dlg.pushButtonLargeur7.setStyleSheet(CUSTOM_WIDGETS[0])
                self.dlg.pushButtonValiderTransaction.setEnabled(True)
                self.dlg.pushButtonActualiseSelection.setEnabled(True)
                self.dico_attributs_modifie[LARGEUR] = "7"
        except TypeError:
            self.dlg.pushButtonLargeur7.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dico_attributs_modifie[LARGEUR] = "7"
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
        self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[2])
        self.dlg.lineEditLargeur.setText("7")

    def setLargeur5(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnLargeur, "pushButtonLargeur5")

        # mettre en rose
        # try : gestion de la valeur "NULL" dans une clé de type nombre
        try:
            if 3.5<self.dico_attributs_commun[LARGEUR] <= 6.5:
                # self.dlg.pushButtonValiderTransaction.setEnabled(False)
                # self.dlg.pushButtonActualiseSelection.setEnabled(False)
                # mettre en vert
                self.dlg.pushButtonLargeur5.setStyleSheet(CUSTOM_WIDGETS[1])

                try:
                    del self.dico_attributs_modifie[LARGEUR]
                except KeyError:
                    pass

                if len(self.dico_attributs_modifie) == 0:
                    self.dlg.pushButtonValiderTransaction.setEnabled(False)
                    self.dlg.pushButtonActualiseSelection.setEnabled(False)

            else:
                self.dlg.pushButtonLargeur5.setStyleSheet(CUSTOM_WIDGETS[0])
                self.dlg.pushButtonValiderTransaction.setEnabled(True)
                self.dlg.pushButtonActualiseSelection.setEnabled(True)
                self.dico_attributs_modifie[LARGEUR] = "5"
        except TypeError:
            self.dlg.pushButtonLargeur5.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dico_attributs_modifie[LARGEUR] = "5"
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
        self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[2])
        self.dlg.lineEditLargeur.setText("5")




    def setLargeur3(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnLargeur, "pushButtonLargeur3")
        # laisser en vert
        # try : gestion de la valeur "NULL" dans une clé de type nombre
        try:
            if 2<self.dico_attributs_commun[LARGEUR] <= 3.5:
                # self.dlg.pushButtonValiderTransaction.setEnabled(False)
                # self.dlg.pushButtonActualiseSelection.setEnabled(False)
                self.dlg.pushButtonLargeur3.setStyleSheet(CUSTOM_WIDGETS[1])
                try:
                    del self.dico_attributs_modifie[LARGEUR]
                except KeyError:
                    pass

                if len(self.dico_attributs_modifie) == 0:
                    self.dlg.pushButtonValiderTransaction.setEnabled(False)
                    self.dlg.pushButtonActualiseSelection.setEnabled(False)
            # mettre en rose
            else:
                self.dlg.pushButtonLargeur3.setStyleSheet(CUSTOM_WIDGETS[0])
                self.dlg.pushButtonValiderTransaction.setEnabled(True)
                self.dlg.pushButtonActualiseSelection.setEnabled(True)
                self.dico_attributs_modifie[LARGEUR] = "3"
        except TypeError:
            self.dlg.pushButtonLargeur3.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dico_attributs_modifie[LARGEUR] = "3"
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
        self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[2])
        self.dlg.lineEditLargeur.setText("3")

    def setLargeurVide(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnLargeur, "pushButtonLargeurVide")

        # try : gestion de la valeur "NULL" dans une clé de type nombre
        try:
            # if self.dico_attributs_commun[LARGEUR] == "NULL" or self.dico_attributs_commun[LARGEUR] == 0:
            if self.dico_attributs_commun[LARGEUR] == "NULL" or self.dico_attributs_commun[LARGEUR] == 0:
                # self.dlg.pushButtonValiderTransaction.setEnabled(False)
                # self.dlg.pushButtonActualiseSelection.setEnabled(False)
                self.dlg.pushButtonLargeurVide.setStyleSheet(CUSTOM_WIDGETS[1])

                try:
                    del self.dico_attributs_modifie[LARGEUR]
                except KeyError:
                    pass

                if len(self.dico_attributs_modifie) == 0:
                    self.dlg.pushButtonValiderTransaction.setEnabled(False)
                    self.dlg.pushButtonActualiseSelection.setEnabled(False)

            else:
                # passe en rose
                self.dlg.pushButtonLargeurVide.setStyleSheet(CUSTOM_WIDGETS[0])
                self.dico_attributs_modifie[LARGEUR] = "NULL"
                self.dlg.pushButtonValiderTransaction.setEnabled(True)
                self.dlg.pushButtonActualiseSelection.setEnabled(True)
        except ValueError:
            # if modif:
            # afficheerreur(ValueError)
            self.dlg.pushButtonLargeurVide.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[LARGEUR] = "NULL"
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
        self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[2])
        self.dlg.lineEditLargeur.setText("")

    def setImportance1(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnImportance, "pushButtonImportance1")
        if self.dico_attributs_commun[IMPORTANCE] == "1":
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonImportance1.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[IMPORTANCE]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonImportance1.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[IMPORTANCE] = "1"


    def setImportance2(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnImportance, "pushButtonImportance2")
        if self.dico_attributs_commun[IMPORTANCE] == "2":
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonImportance2.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[IMPORTANCE]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonImportance2.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[IMPORTANCE] = "2"


    def setImportance3(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnImportance, "pushButtonImportance3")
        if self.dico_attributs_commun[IMPORTANCE] == "3":
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonImportance3.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[IMPORTANCE]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonImportance3.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[IMPORTANCE] = "3"



    def setImportance4(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnImportance, "pushButtonImportance4")
        if self.dico_attributs_commun[IMPORTANCE] == "4":
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonImportance4.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[IMPORTANCE]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)

        else:
            self.dlg.pushButtonImportance4.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[IMPORTANCE] = "4"

    def setImportance5(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnImportance, "pushButtonImportance5")
        if self.dico_attributs_commun[IMPORTANCE] == "5":
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonImportance5.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[IMPORTANCE]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonImportance5.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dico_attributs_modifie[IMPORTANCE] = "5"
            self.dlg.pushButtonActualiseSelection.setEnabled(True)

    def setImportance6(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnImportance, "pushButtonImportance6")
        if self.dico_attributs_commun[IMPORTANCE] == "6":

            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonImportance6.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[IMPORTANCE]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.set_attributs_defaut(IMPORTANCE)
            self.dlg.pushButtonImportance6.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[IMPORTANCE] = "6"

    def setDoubleSens(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnSens, "pushButtonDoubleSens")
        if self.dico_attributs_commun[SENS] == DOUBLE_SENS:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonDoubleSens.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[SENS]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonDoubleSens.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[SENS] = DOUBLE_SENS

    def setSensUnique(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnSens, "pushButtonSensUnique")
        # if self.dico_attributs_commun[SENS] == SENS_DIRECT or self.dico_attributs_commun[SENS] == SENS_INVERSE:
        if self.dico_attributs_commun[SENS] == SENS_UNIQUE \
                or self.dico_attributs_commun[SENS] == SENS_DIRECT\
                or self.dico_attributs_commun[SENS] == SENS_INVERSE:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonSensUnique.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[SENS]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonSensUnique.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[SENS] = SENS_DIRECT

    def setInverserSens(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnSens, "pushButtonInverserSens")
        # si sens direct on change en sens inverse et inversement
        idchamps = self.layer.fields().indexFromName(SENS)
        # self.layer.startEditing()
        for selection in self.listeSelection:
            attr = selection.attributes()
            sens = attr[idchamps]
            if sens == SENS_DIRECT:
                self.dico_attributs_modifie[SENS] = SENS_INVERSE
            elif sens == SENS_INVERSE:
                self.dico_attributs_modifie[SENS] = SENS_DIRECT
            else:
                afficheerreur("Ce tronçon n'est pas en sens unique, il ne sera pas modifié")
                self.dlg.pushButtonInverserSens.setStyleSheet(CUSTOM_WIDGETS[2])
                return

        self.dlg.pushButtonInverserSens.setStyleSheet(CUSTOM_WIDGETS[0])
        self.dlg.pushButtonValiderTransaction.setEnabled(True)
        self.dlg.pushButtonActualiseSelection.setEnabled(True)

    def setSensSansObjet(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnSens, "pushButtonSensSansObjet")
        if self.dico_attributs_commun[SENS] == SANS_OBJET:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonSensSansObjet.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[SENS]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonSensSansObjet.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[SENS] = SANS_OBJET
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)


    def setSensSansValeur(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnSens, "pushButtonSensSansVal")
        if self.dico_attributs_commun[SENS] == "":
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonSensSansVal.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[SENS]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonSensSansVal.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[SENS] = ""
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)

    def setAccesLibre(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnAcces, "pushButtonAccesLibre")
        if self.dico_attributs_commun[ACCES] == ACCES_LIBRE:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonAccesLibre.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[ACCES]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonAccesLibre.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[ACCES] = ACCES_LIBRE
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)

    def setAccesRestreint(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnAcces, "pushButtonAccesRestreint")
        if self.dico_attributs_commun[ACCES] == ACCES_RESTREINT:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonAccesRestreint.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[ACCES]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonAccesRestreint.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[ACCES] = ACCES_RESTREINT
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)

    def setAccesImpossible(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(self.listbtnAcces, "pushButtonAccesImpossible")
        if self.dico_attributs_commun[ACCES] == ACCES_IMPOSSIBLE:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonAccesImpossible.setStyleSheet(CUSTOM_WIDGETS[1])

            try:
                del self.dico_attributs_modifie[ACCES]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.set_attributs_defaut(ACCES_IMPOSSIBLE)
            self.dlg.pushButtonAccesImpossible.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[ACCES] = ACCES_IMPOSSIBLE
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)



    def get_nb_selection(self):
        return self.layer.selectedFeatureCount()

    def __init__(self, iface):
        # TODO __init__
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """

        # declaration :dialogue
        self.dlgAProposDe = None
        self.dlg = None

        # boolean pour afficher/masquer le sens de numerisation
        self.is_affiche_sens_num = False

        self.ismodifie = False

        self.NatureAllIdentique = ""

        self.listbtnNature = ["pushButtonRte2Chaussee", "pushButtonRte1Chaussee", "pushButtonEmpierree",
                              "pushButtonChemin", "pushButtonSentier", "pushButtonRondpoint"]
        self.listbtnNbVoies = ["pushButton3voies", "pushButton2voies", "pushButton1voie", "pushButtonVoieSansObjet"]
        # l'editlargeur est geré independement car aspect different
        self.listbtnLargeur = ["pushButtonLargeur14","pushButtonLargeur10","pushButtonLargeur7","pushButtonLargeur5",
                               "pushButtonLargeur3", "pushButtonLargeurVide"]
        self.listbtnImportance = ["pushButtonImportance1", "pushButtonImportance2", "pushButtonImportance3",
                                  "pushButtonImportance4", "pushButtonImportance5", "pushButtonImportance6"]
        self.listbtnSens = ["pushButtonDoubleSens", "pushButtonSensUnique", "pushButtonInverserSens",
                            "pushButtonSensSansObjet", "pushButtonSensSansVal"]
        self.listbtnAcces = ["pushButtonAccesLibre", "pushButtonAccesRestreint", "pushButtonAccesImpossible"]

        self.listBtnTotal = self.listbtnNature.copy()
        self.listBtnTotal += self.listbtnNbVoies.copy()
        self.listBtnTotal += self.listbtnLargeur.copy()
        self.listBtnTotal += self.listbtnImportance.copy()
        self.listBtnTotal += self.listbtnSens.copy()
        self.listBtnTotal += self.listbtnAcces.copy()

        self.iface = iface
        # Save reference to the QGIS interface
        self.layer = None

        self.cheminpluscourt = None

        self.listeSelection = None

        # dictionnaire pour gerer les attributs de la selection
        # clé = identifiant
        self.dico_attributs_selection = {}

        # dico des attributs commun
        self.dico_attributs_commun = {}

        # dico des boutons correspondant aux attributs commun
        # pour garder l'aspect initial des boutons dans l'interfac
        self.dico_btn_initial = {}

        # dico pour stocker les attributs modifiés
        self.dico_attributs_modifie = {}

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ChangeAttributRoute_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

    # met en rose les attributs par defauts en fonction de la nature
    def set_attributs_defaut(self,attribut):
        # TODO set_attributs_defaut
        self.initbtnclic(self.listBtnTotal)

        if attribut == RTE_2_CHAUSSEES:
            self.dlg.pushButtonSensUnique.setStyleSheet(CUSTOM_WIDGETS[0])
            # self.dico_attributs_modifie[SENS] = SENS_DIRECT

        if attribut == RTE_EMPIERREE or attribut == CHEMIN:
            self.dico_attributs_modifie[NB_VOIES] = SANS_OBJET
            self.dlg.pushButtonVoieSansObjet.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonLargeurVide.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[LARGEUR] = "NULL"
            # self.dico_attributs_modifie[IMPORTANCE] = "5"
            # on passe l'edit largeur en blanc aussi
            self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[2])

            self.dlg.pushButtonDoubleSens.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[SENS] = DOUBLE_SENS

        if attribut == SENTIER:
            self.dico_attributs_modifie[NB_VOIES] = SANS_OBJET
            self.dlg.pushButtonVoieSansObjet.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonLargeurVide.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[LARGEUR] = "NULL"
            # on passe l'edit largeur en blanc aussi
            self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[2])

            self.dlg.pushButtonImportance6.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[IMPORTANCE] = "6"
            self.dlg.pushButtonSensSansObjet.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[SENS] = SANS_OBJET
            self.dlg.pushButtonAccesImpossible.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[ACCES] = ACCES_IMPOSSIBLE

        if attribut == ROND_POINT:
            self.dlg.pushButtonSensUnique.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[SENS] = SENS_DIRECT

        if attribut == ACCES_IMPOSSIBLE:
            self.dlg.pushButtonImportance6.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[IMPORTANCE] = "6"

        if attribut == IMPORTANCE:
            if self.dico_attributs_commun[NATURE] == RTE_1_CHAUSSEE:
                self.dlg.pushButtonSensSansVal.setStyleSheet(CUSTOM_WIDGETS[0])
                self.dico_attributs_modifie[SENS] = ""




    # rempli un dico avec uniquement les attributs communs
    # sinon "***" à la place des attributs non communs
    def set_attributs_commun(self):
        # TODO set_attributs_commun

        cleabs_selection = []
        nature_selection = []
        nbvoies_selection = []
        largeur_selection = []
        importance_selection = []
        sens_selection = []
        acces_selection = []
        # chaques listes contient tous les attributs correspondant au champ choisi
        # avec doublons eventuel
        for cle,valeur in self.dico_attributs_selection.items():
            cleabs_selection.append(valeur[0])
            nature_selection.append(valeur[1])
            nbvoies_selection.append(valeur[2])
            largeur_selection.append(valeur[3])
            importance_selection.append(valeur[4])
            sens_selection.append(valeur[5])
            acces_selection.append(valeur[6])

        # set : list des attributs UNIQUE
        # len, renvoi la taille, donc si renvoi 1 = un champ commun
        # ....._selection : liste contenant tous les attributs de chaque entité sélectionnés
        # NATURE
        if len(set(nature_selection)) != 1:
            self.dico_attributs_commun[NATURE] = "***"
            self.dico_btn_initial[NATURE] = "***"
        else:
            self.dico_attributs_commun[NATURE] = nature_selection[0]
            if nature_selection[0] == RTE_2_CHAUSSEES:
                self.dico_btn_initial[NATURE] = "pushButtonRte2Chaussee"
            if nature_selection[0] == RTE_1_CHAUSSEE:
                self.dico_btn_initial[NATURE] = "pushButtonRte1Chaussee"
            if nature_selection[0] == RTE_EMPIERREE:
                self.dico_btn_initial[NATURE] = "pushButtonEmpierree"
            if nature_selection[0] == CHEMIN:
                self.dico_btn_initial[NATURE] = "pushButtonChemin"
            if nature_selection[0] == SENTIER:
                self.dico_btn_initial[NATURE] = "pushButtonSentier"
            if nature_selection[0] == ROND_POINT:
                self.dico_btn_initial[NATURE] = "pushButtonRondpoint"
        # NBVOIES
        if len(set(nbvoies_selection)) != 1:
            self.dico_attributs_commun[NB_VOIES] = "***"
            self.dico_btn_initial[NB_VOIES] = "***"
        else:
            self.dico_attributs_commun[NB_VOIES] = nbvoies_selection[0]
            if nbvoies_selection[0] == "3":
                self.dico_btn_initial[NB_VOIES] = "pushButton3voies"
            if nbvoies_selection[0] == "2":
                self.dico_btn_initial[NB_VOIES] = "pushButton2voies"
            if nbvoies_selection[0] == "1":
                self.dico_btn_initial[NB_VOIES] = "pushButton1voie"
            if nbvoies_selection[0] == SANS_OBJET:
                self.dico_btn_initial[NB_VOIES] = "pushButtonVoieSansObjet"


        # LARGEUR
        if len(set(largeur_selection)) != 1:
            self.dico_attributs_commun[LARGEUR] = "***"
            self.dico_btn_initial[LARGEUR] = "***"
            self.dlg.lineEditLargeur.setText("")
        else:
            self.dico_attributs_commun[LARGEUR] = largeur_selection[0]
            self.dlg.lineEditLargeur.setText(str(largeur_selection[0]))

            try:
                if largeur_selection[0] > 12.5:
                    self.dico_btn_initial[LARGEUR] = "pushButtonLargeur14"
                elif 9<largeur_selection[0]<=12.5:
                    self.dico_btn_initial[LARGEUR] = "pushButtonLargeur10"
                elif 6.5<largeur_selection[0]<=9:
                    self.dico_btn_initial[LARGEUR] = "pushButtonLargeur7"
                elif 3.5<largeur_selection[0] <= 6.5:
                    self.dico_btn_initial[LARGEUR] = "pushButtonLargeur5"
                elif 0<largeur_selection[0] <= 3.5:
                    self.dico_btn_initial[LARGEUR] = "pushButtonLargeur3"
                # TODO : a voir ici pb de largeur NULL , pk l'egalité n'est pas verifié ?
                # il faut donner quoi comme valeur pour avoir "NULL" ??
                elif largeur_selection[0] == "NULL":
                    self.dico_btn_initial[LARGEUR] = "pushButtonLargeurVide"
                elif largeur_selection[0] == None:
                    self.dico_btn_initial[LARGEUR] = "pushButtonLargeurVide"




            except TypeError:
                self.dico_btn_initial[LARGEUR] = "pushButtonLargeurVide"
            except ValueError:
                self.dico_btn_initial[LARGEUR] = "pushButtonLargeurVide"

            self.dlg.lineEditLargeur.setText(str(largeur_selection[0]))



        # IMPORTANCE
        if len(set(importance_selection)) != 1:
            self.dico_attributs_commun[IMPORTANCE] = "***"
            self.dico_btn_initial[IMPORTANCE] = "***"
        else:
            self.dico_attributs_commun[IMPORTANCE] = importance_selection[0]
            if importance_selection[0] == "1":
                self.dico_btn_initial[IMPORTANCE] = "pushButtonImportance1"
            if nbvoies_selection[0] == "2":
                self.dico_btn_initial[IMPORTANCE] = "pushButtonImportance2"
            if importance_selection[0] == "3":
                self.dico_btn_initial[IMPORTANCE] = "pushButtonImportance3"
            if importance_selection[0] == "4":
                self.dico_btn_initial[IMPORTANCE] = "pushButtonImportance4"
            if importance_selection[0] == "5":
                self.dico_btn_initial[IMPORTANCE] = "pushButtonImportance5"
            if importance_selection[0] == "6":
                self.dico_btn_initial[IMPORTANCE] = "pushButtonImportance6"

        # SENS
        # different ici car sens direct OU sens inverse c'est pareil
        nb_sens_unique = sens_selection.count(SENS_DIRECT) + sens_selection.count(SENS_INVERSE)
        # que des sens directe ou sens inverse
        if self.get_nb_selection() != 0 and (nb_sens_unique == len(sens_selection)):
            self.dico_attributs_commun[SENS] = SENS_UNIQUE
            self.dico_btn_initial[SENS] = "pushButtonSensUnique"
            # pas de valeurs communes
        elif len(set(sens_selection)) != 1:
            self.dico_attributs_commun[SENS] = "***"
            self.dico_btn_initial[SENS] = "***"
        else:
            self.dico_attributs_commun[SENS] = sens_selection[0]
            if sens_selection[0] == DOUBLE_SENS:
                self.dico_btn_initial[SENS] = "pushButtonDoubleSens"
            if sens_selection[0] == SANS_OBJET:
                self.dico_btn_initial[SENS] = "pushButtonSensSansObjet"
            if sens_selection[0] == "":
                self.dico_btn_initial[SENS] = "pushButtonSensSansVal"

        # ACCES
        if len(set(acces_selection)) != 1:
            self.dico_attributs_commun[ACCES] = "***"
            self.dico_btn_initial[ACCES] = "***"
        else:
            self.dico_attributs_commun[ACCES] = acces_selection[0]
            if acces_selection[0] == ACCES_LIBRE:
                self.dico_btn_initial[ACCES] = "pushButtonAccesLibre"
            if acces_selection[0] == ACCES_RESTREINT:
                self.dico_btn_initial[ACCES] = "pushButtonAccesRestreint"
            if acces_selection[0] == ACCES_IMPOSSIBLE:
                self.dico_btn_initial[ACCES] = "pushButtonAccesImpossible"

        # les attributs communs seront renseignés, les autres auront "***"
        return self.dico_attributs_commun

    """**********************************
    defini un dictionnaire d'attributs
    clé : identifiant des entités
    valeurs : attributs
    *************************************"""
    def set_attributs_selection(self):
        # TODO set_attributs_selection

        idcleabs = self.layer.fields().indexFromName(CLEABS)
        idnature = self.layer.fields().indexFromName(NATURE)
        idnbvoies = self.layer.fields().indexFromName(NB_VOIES)
        idlargeur = self.layer.fields().indexFromName(LARGEUR)
        idimportance = self.layer.fields().indexFromName(IMPORTANCE)
        idsens = self.layer.fields().indexFromName(SENS)
        idacces = self.layer.fields().indexFromName(ACCES)

        self.dico_attributs_selection.clear()
        for entite in self.listeSelection:
            attr = entite.attributes()
            ident = entite.id()
            self.dico_attributs_selection[ident] = [attr[idcleabs],
                        attr[idnature],
                        attr[idnbvoies],
                        attr[idlargeur],
                        attr[idimportance],
                        attr[idsens],
                        attr[idacces]]
        return self.dico_attributs_selection


    def set_activeLayerRoute(self,message = True):
        # TODO set_activeLayerRoute
        project = QgsProject.instance()
        layer = project.mapLayersByName(LAYER_ROUTE)
        if not layer:
            if message:
                afficheerreur(f"la couche \"{LAYER_ROUTE}\" n'existe pas",TITRE_INTERFACE)
            return False
        else:
            self.iface.setActiveLayer(layer[0])
            self.layer = self.iface.activeLayer()
            return True

    # initialiser les boutons en rose lorsqu'ils sont pressés
    # passe tous les boutons d'un groupe par defaut avant de mettre en rose celui en parametre
    def initbtnclic(self, listgroupebtn, btnclick=""):
        # TODO initbtnclic

        for i, btn in enumerate(self.dlg.findChildren(QPushButton)):
            # juste les boutons de l'interface correspondant à la list de boutons passé en parametre
            if btn.objectName() in listgroupebtn:
                # 2 : pas de fond
                btn.setStyleSheet(CUSTOM_WIDGETS[2])
                # btn.setStyleSheet("font - weight: lighter")
                if btnclick == btn.objectName():
                    # 0 : fond rose
                    # afficheerreur(btnclick)

                    btn.setStyleSheet(CUSTOM_WIDGETS[0])

        # garder en "vert" les boutons initiaux
        for attribut in self.dico_btn_initial.values():
            if attribut != "***":
                btn = self.dlg.findChild(QPushButton,attribut)
                btn.setStyleSheet(CUSTOM_WIDGETS[1])
                # afficheerreur(btn.objectName())

    def get_bouton_nature_actif(self):
        # TODO get_bouton_nature_actif
        nature = None
        for val in self.dico_attributs_selection.values():
            nature =  val[1]
        return nature



    def controleDonnees(self, nature):
        # TODO controleDonnees

        if nature == RTE_2_CHAUSSEES:
            self.dlg.pushButtonImportance6.setEnabled(False)
            self.dlg.pushButtonImportance6.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonVoieSansObjet.setEnabled(False)
            self.dlg.pushButtonVoieSansObjet.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeurVide.setEnabled(False)
            self.dlg.pushButtonLargeurVide.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonInverserSens.setEnabled(False)
            self.dlg.pushButtonInverserSens.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonSensSansObjet.setEnabled(False)
            self.dlg.pushButtonSensSansObjet.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonSensSansVal.setEnabled(False)
            self.dlg.pushButtonSensSansVal.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonDoubleSens.setEnabled(False)
            self.dlg.pushButtonDoubleSens.setStyleSheet(CUSTOM_WIDGETS[6])
        if nature == RTE_1_CHAUSSEE:
            self.dlg.pushButtonVoieSansObjet.setEnabled(False)
            self.dlg.pushButtonVoieSansObjet.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeurVide.setEnabled(False)
            self.dlg.pushButtonLargeurVide.setStyleSheet(CUSTOM_WIDGETS[6])

        if nature == RTE_EMPIERREE:
            # self.setvoieSansObj(False)
            # self.setLargeurVide(False)

            self.dlg.pushButtonSensUnique.setEnabled(False)
            self.dlg.pushButtonSensUnique.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonInverserSens.setEnabled(False)
            self.dlg.pushButtonInverserSens.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonSensSansObjet.setEnabled(False)
            self.dlg.pushButtonSensSansObjet.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonSensSansVal.setEnabled(False)
            self.dlg.pushButtonSensSansVal.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButton1voie.setEnabled(False)
            self.dlg.pushButton1voie.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButton2voies.setEnabled(False)
            self.dlg.pushButton2voies.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButton3voies.setEnabled(False)
            self.dlg.pushButton3voies.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur14.setEnabled(False)
            self.dlg.pushButtonLargeur14.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur10.setEnabled(False)
            self.dlg.pushButtonLargeur10.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur7.setEnabled(False)
            self.dlg.pushButtonLargeur7.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur5.setEnabled(False)
            self.dlg.pushButtonLargeur5.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur3.setEnabled(False)
            self.dlg.pushButtonLargeur3.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonImportance1.setEnabled(False)
            self.dlg.pushButtonImportance1.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonImportance2.setEnabled(False)
            self.dlg.pushButtonImportance2.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonImportance3.setEnabled(False)
            self.dlg.pushButtonImportance3.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonImportance4.setEnabled(False)
            self.dlg.pushButtonImportance4.setStyleSheet(CUSTOM_WIDGETS[6])

        if nature == CHEMIN:
            # self.setvoieSansObj(False)
            # self.setLargeurVide(False)
            # self.setDoubleSens(False)

            self.dlg.pushButtonSensUnique.setEnabled(False)
            self.dlg.pushButtonSensUnique.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonInverserSens.setEnabled(False)
            self.dlg.pushButtonInverserSens.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonSensSansObjet.setEnabled(False)
            self.dlg.pushButtonSensSansObjet.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonSensSansVal.setEnabled(False)
            self.dlg.pushButtonSensSansVal.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButton1voie.setEnabled(False)
            self.dlg.pushButton1voie.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButton2voies.setEnabled(False)
            self.dlg.pushButton2voies.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButton3voies.setEnabled(False)
            self.dlg.pushButton3voies.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur14.setEnabled(False)
            self.dlg.pushButtonLargeur14.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur10.setEnabled(False)
            self.dlg.pushButtonLargeur10.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur7.setEnabled(False)
            self.dlg.pushButtonLargeur7.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur5.setEnabled(False)
            self.dlg.pushButtonLargeur5.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur3.setEnabled(False)
            self.dlg.pushButtonLargeur3.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonImportance1.setEnabled(False)
            self.dlg.pushButtonImportance1.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonImportance2.setEnabled(False)
            self.dlg.pushButtonImportance2.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonImportance3.setEnabled(False)
            self.dlg.pushButtonImportance3.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonImportance4.setEnabled(False)
            self.dlg.pushButtonImportance4.setStyleSheet(CUSTOM_WIDGETS[6])

        if nature == SENTIER:
            # self.setvoieSansObj(False)
            # self.setLargeurVide(False)
            # self.setImportance6(False)
            # self.setSensSansObjet(False)
            # self.setAccesImpossible(False)

            self.dlg.pushButtonDoubleSens.setEnabled(False)
            self.dlg.pushButtonDoubleSens.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonSensUnique.setEnabled(False)
            self.dlg.pushButtonSensUnique.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonInverserSens.setEnabled(False)
            self.dlg.pushButtonInverserSens.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonSensSansVal.setEnabled(False)
            self.dlg.pushButtonSensSansVal.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur14.setEnabled(False)
            self.dlg.pushButtonLargeur14.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur10.setEnabled(False)
            self.dlg.pushButtonLargeur10.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur7.setEnabled(False)
            self.dlg.pushButtonLargeur7.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur5.setEnabled(False)
            self.dlg.pushButtonLargeur5.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeur3.setEnabled(False)
            self.dlg.pushButtonLargeur3.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonAccesLibre.setEnabled(False)
            self.dlg.pushButtonAccesLibre.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonAccesRestreint.setEnabled(False)
            self.dlg.pushButtonAccesRestreint.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonImportance1.setEnabled(False)
            self.dlg.pushButtonImportance1.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonImportance2.setEnabled(False)
            self.dlg.pushButtonImportance2.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonImportance3.setEnabled(False)
            self.dlg.pushButtonImportance3.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonImportance4.setEnabled(False)
            self.dlg.pushButtonImportance4.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonImportance5.setEnabled(False)
            self.dlg.pushButtonImportance5.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButton1voie.setEnabled(False)
            self.dlg.pushButton1voie.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButton2voies.setEnabled(False)
            self.dlg.pushButton2voies.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButton3voies.setEnabled(False)
            self.dlg.pushButton3voies.setStyleSheet(CUSTOM_WIDGETS[6])

        if nature == ROND_POINT:
            # self.setSensUnique(False)

            self.dlg.pushButtonImportance6.setEnabled(False)
            self.dlg.pushButtonImportance6.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonLargeurVide.setEnabled(False)
            self.dlg.pushButtonLargeurVide.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonVoieSansObjet.setEnabled(False)
            self.dlg.pushButtonVoieSansObjet.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonDoubleSens.setEnabled(False)
            self.dlg.pushButtonDoubleSens.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonSensSansVal.setEnabled(False)
            self.dlg.pushButtonSensSansVal.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonSensSansObjet.setEnabled(False)
            self.dlg.pushButtonSensSansObjet.setStyleSheet(CUSTOM_WIDGETS[6])
            self.dlg.pushButtonInverserSens.setEnabled(False)
            self.dlg.pushButtonInverserSens.setStyleSheet(CUSTOM_WIDGETS[6])

    def activerBoutons(self, affiche):
        # nature
        self.dlg.pushButtonRte2Chaussee.setEnabled(affiche)
        self.dlg.pushButtonRte1Chaussee.setEnabled(affiche)
        self.dlg.pushButtonEmpierree.setEnabled(affiche)
        self.dlg.pushButtonChemin.setEnabled(affiche)
        self.dlg.pushButtonSentier.setEnabled(affiche)
        self.dlg.pushButtonRondpoint.setEnabled(affiche)

        # nb voie
        self.dlg.pushButtonVoieSansObjet.setEnabled(affiche)
        self.dlg.pushButton1voie.setEnabled(affiche)
        self.dlg.pushButton2voies.setEnabled(affiche)
        self.dlg.pushButton3voies.setEnabled(affiche)

        # largeur
        self.dlg.pushButtonLargeur14.setEnabled(affiche)
        self.dlg.pushButtonLargeur10.setEnabled(affiche)
        self.dlg.pushButtonLargeur7.setEnabled(affiche)
        self.dlg.pushButtonLargeur5.setEnabled(affiche)
        self.dlg.pushButtonLargeur3.setEnabled(affiche)
        self.dlg.pushButtonLargeurVide.setEnabled(affiche)
        self.dlg.lineEditLargeur.setEnabled(affiche)

        # importance
        self.dlg.pushButtonImportance1.setEnabled(affiche)
        self.dlg.pushButtonImportance2.setEnabled(affiche)
        self.dlg.pushButtonImportance3.setEnabled(affiche)
        self.dlg.pushButtonImportance4.setEnabled(affiche)
        self.dlg.pushButtonImportance5.setEnabled(affiche)
        self.dlg.pushButtonImportance6.setEnabled(affiche)

        # sens
        self.dlg.pushButtonDoubleSens.setEnabled(affiche)
        self.dlg.pushButtonSensUnique.setEnabled(affiche)
        self.dlg.pushButtonInverserSens.setEnabled(affiche)
        self.dlg.pushButtonSensSansObjet.setEnabled(affiche)
        self.dlg.pushButtonSensSansVal.setEnabled(affiche)

        # acces
        self.dlg.pushButtonAccesLibre.setEnabled(affiche)
        self.dlg.pushButtonAccesRestreint.setEnabled(affiche)
        self.dlg.pushButtonAccesImpossible.setEnabled(affiche)

    # retourne la valeur du champs par defaut OU modifié
    def get_valeur_from_champs(self,nature):
        if self.dico_attributs_modifie.get(nature) is None:
            return self.dico_attributs_commun.get(nature)
        else:
            return self.dico_attributs_modifie.get(nature)


    def test_valeur_valide(self):

        str_erreur = ""
        # if self.dlg.lineEditLargeur.text() == "":
        #     str_erreur += "La largeur ne peut pas etre vide\n"

        # TEST SUR champs commun a :RTE_2_CHAUSSEE et RTE_1_CHAUSSEE
        if (self.dico_attributs_modifie.get(NATURE) == RTE_2_CHAUSSEES or
            self.dico_attributs_modifie.get(NATURE) == RTE_1_CHAUSSEE):
            # test sur le nombre de voies
            if (self.get_valeur_from_champs(NB_VOIES) == SANS_OBJET or
                    self.get_valeur_from_champs(NB_VOIES) is None or
                    self.get_valeur_from_champs(NB_VOIES) == "***"):
                str_erreur += "Veuillez renseigner un nombre de voies\n"
            # test sur largeur
            if (self.get_valeur_from_champs(LARGEUR) == "NULL" or
                    self.get_valeur_from_champs(LARGEUR) == "***"):
                str_erreur += "Veuillez renseigner une largeur de chaussée\n"
        #  TEST en plus sur RTE_2_CHAUSSEE
            # test sur l'importance
            if self.get_valeur_from_champs(IMPORTANCE) == "6":
                str_erreur = "Veuillez renseigner une importance différente de 6"


        # TEST sur route empierrée
        # if self.dico_attributs_modifie.get(NATURE) == RTE_EMPIERREE:
        #     print("test ", self.get_valeur_from_champs(IMPORTANCE))
        #     if (self.get_valeur_from_champs(IMPORTANCE) != "5" or
        #             self.get_valeur_from_champs(IMPORTANCE) != "6"):
        #         str_erreur += f"L'importance doit être egal à <span style = 'color:red'><b>5</b></span> ou <span style = 'color:red'><b>6</b></span>\n"



        # TEST SUR champs :ROND_POINT
        if self.dico_attributs_modifie.get(NATURE) == ROND_POINT:
            # test sur le nombre de voies
            if (self.get_valeur_from_champs(NB_VOIES) == SANS_OBJET or
                    self.get_valeur_from_champs(NB_VOIES) is None or
                    self.get_valeur_from_champs(NB_VOIES) == "***"):
                str_erreur += "Veuillez renseigner un nombre de voies\n"
            # test sur largeur
            if (self.get_valeur_from_champs(LARGEUR) == "NULL" or
                    self.get_valeur_from_champs(LARGEUR) == "***"):
                str_erreur += "Veuillez renseigner une largeur de chaussée\n"

        if str_erreur != "":
            afficheerreur(str_erreur)
            return False
        else:
            return True

    def colorchange(self):
        self.actualiserSelection()

    # test si un attribut modifié est deja dans les attributs de la selection
    def modifie_isin_selection(self,attribut):
        # TODO modifie_isin_selection
        for sel in self.dico_attributs_selection.values():
            if attribut == sel[1]:
                return True
            else:
                return False

    def validerLaTransaction(self):
        # tester les valeurs possible ou interdite en fonction de la nature
        # return false si les valeurs ne sont pas valides
        if not self.test_valeur_valide():
            return

        # print("Attributs modifiés : ",self.dico_attributs_modifie)

        self.layer.startEditing()

        # dico temp pour avoir le meme "format" que le dico_attributs_modifie
        dico_sel_temp = {}

        for ident,valeur_sel in self.dico_attributs_selection.items():

            dico_sel_temp[CLEABS] = valeur_sel[0]
            dico_sel_temp[NATURE] = valeur_sel[1]
            dico_sel_temp[NB_VOIES] = valeur_sel[2]
            dico_sel_temp[LARGEUR] = valeur_sel[3]
            dico_sel_temp[IMPORTANCE] = valeur_sel[4]
            dico_sel_temp[SENS] = valeur_sel[5]
            dico_sel_temp[ACCES] = valeur_sel[6]

            for champs, valeur in self.dico_attributs_modifie.items():
                idchamps = self.layer.fields().indexFromName(champs)

                self.layer.changeAttributeValue(ident, idchamps, valeur)

        self.dico_attributs_modifie.clear()
        self.ismodifie = False
        self.actualiserSelection()

    def actualiserSelection(self):

        # remettre le fond par defaut
        self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[2])

        self.dlg.pushButtonValiderTransaction.setEnabled(False)
        self.dlg.pushButtonchepluscourt.setEnabled(False)

        self.listeSelection = self.layer.selectedFeatures()
        # self.nbselection = self.layer.selectedFeatureCount()
        self.get_nb_selection()
        # self.dlg.labelNbSelection.setText(str(self.get_nb_selection()))
        self.dlg.labelNbSelection.setText(f"Vous avez sélectionné : <span style='color: red'><b>{self.get_nb_selection()}</b></span> tronçon(s)")


        # gestion de la couleur de selection
        couleur = self.dlg.mColorButton.color()
        self.iface.mapCanvas().setSelectionColor(couleur)

        # sauvegarde des attributs de la selection
        self.set_attributs_selection()


        # initialise un dico avec les attributs commun, à faire APRES set_attributs_selection
        self.set_attributs_commun()

        self.dico_attributs_modifie.clear()

        # initialise juste tous boutons en gras (aucun n'est sélectionné)
        # et met en vert les attributs de la sélection
        self.initbtnclic(self.listBtnTotal)


        if self.get_nb_selection() <1:
            self.activerBoutons(False)
        else:
            self.activerBoutons(True)

        self.controleDonnees(self.get_bouton_nature_actif())

        if self.get_nb_selection() == 2:
            self.dlg.pushButtonchepluscourt.setEnabled(True)

        if self.get_nb_selection() == 0:
            self.dlg.lineEditLargeur.setText("")

        self.dlg.pushButtonActualiseSelection.setEnabled(False)

    def editfocus(self):
        # afficheerreur("perte focus")
        pass

    def finedition(self):
        # afficheerreur("fin edition")
        pass


    def click_edit(self,event):
        self.dlg.lineEditLargeur.clear()
        # on garde le bouton de largeur initial en vert
        try:
            btn = self.dlg.findChildren(QPushButton,self.dico_btn_initial[LARGEUR])
            btn[0].setStyleSheet(CUSTOM_WIDGETS[1])
        except IndexError:
            pass

        # on passe tous les bouton largeur en blanc sauf celui qui est vert
        for i,btn in enumerate(self.dlg.findChildren(QPushButton)):
            if btn.objectName() in self.listbtnLargeur and btn.objectName() != self.dico_btn_initial[LARGEUR]:
                btn.setStyleSheet(CUSTOM_WIDGETS[2])

        # on passe l'edit en rose
        self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[5])

        self.dlg.pushButtonValiderTransaction.setEnabled(True)
        self.dlg.pushButtonActualiseSelection.setEnabled(True)



    def textchangelargeur(self):
        # Définir le format du nombre décimal avec un point comme séparateur
        decimal_regex = QRegExp(r"^\d*\.?\d{1}$")  # Autorise un point décimal, pas de virgule
        validator = QRegExpValidator(decimal_regex, self.dlg.lineEditLargeur)
        self.dlg.lineEditLargeur.setValidator(validator)

        if self.get_nb_selection() == 0:
            return

        # self.largeurlineedit = self.dlg.lineEditLargeur.text()
        self.dico_attributs_modifie[LARGEUR] = self.dlg.lineEditLargeur.text()

        # if self.dlg.lineEditLargeur.text() != "":
        # self.dlg.pushButtonValiderTransaction.setEnabled(True)
        # self.dlg.pushButtonActualiseSelection.setEnabled(True)

    def afficher_sens_num(self):
        if self.is_affiche_sens_num:
            self.dlg.pushButtonsensNumerisation.setText("Afficher le sens\n de numerisation")
            self.layer.loadNamedStyle(os.path.join(os.path.dirname(__file__),"SENS_NUM", "sauvegarde_style_route.qml"))
            self.is_affiche_sens_num = False
        else:
            self.dlg.pushButtonsensNumerisation.setText("Masquer le sens\n de numerisation")
            self.layer.saveNamedStyle(os.path.join(os.path.dirname(__file__),"SENS_NUM", "sauvegarde_style_route.qml"))
            self.layer.loadNamedStyle(os.path.join(os.path.dirname(__file__), "SENS_NUM","style_sens_numerisation.qml"))
            self.is_affiche_sens_num = True

        self.layer.triggerRepaint()

    def afficheAProposeDe(self):
        self.dlgAProposDe.show()

    def zoom_selection(self):
        self.iface.actionZoomToSelected().trigger()

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ChangeAttributRoute', message)


    def initGui(self):
        pass

    def unload(self):
        pass

    def keyPressEvent(self, event):
        # if event.key() == Qt.Key_Return or event.key() == Qt.Key_Enter:
        #     afficheerreur("touche entrer")
        pass

    def run(self):
        # TODO run
        """Run method that performs all the real work"""
        projet = QgsProject.instance()
        if len(projet.mapLayers()) <= 0:
            afficheerreur("Aucun projet chargé")
            return
        # activation du layer route s'il existe
        if not self.set_activeLayerRoute():
            return

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started

        self.dlg = ChangeAttributRouteDialog()
        self.dlg.setWindowTitle(f"{TITRE_INTERFACE}  {VERSION}")
        # self.dlg.setStyleSheet(FOND_DIAL)

        self.dlgAProposDe = Aproposde()
        # self.dlgAProposDe.setStyleSheet(FOND_DIAL)
        self.dlgAProposDe.setWindowFlags(Qt.WindowStaysOnTopHint)
        self.dlgAProposDe.pushButtonAffichedoc.clicked.connect(afficheDoc)

        self.cheminpluscourt = cheminpluscourt(self.iface, self.layer)

        self.dlg.mColorButton.setColor(self.iface.mapCanvas().selectionColor())
        self.dlg.mColorButton.colorChanged.connect(self.colorchange)

        # evenement de changement de selection pour actualiser la selection des Qcombobox
        self.iface.mapCanvas().selectionChanged.connect(self.actualiserSelection)
        self.actualiserSelection()

        self.dlg.label_2.setStyleSheet(CUSTOM_WIDGETS[3])
        self.dlg.label_3.setStyleSheet(CUSTOM_WIDGETS[3])
        self.dlg.label_4.setStyleSheet(CUSTOM_WIDGETS[3])
        self.dlg.label_5.setStyleSheet(CUSTOM_WIDGETS[3])
        self.dlg.label_6.setStyleSheet(CUSTOM_WIDGETS[3])
        self.dlg.label_7.setStyleSheet(CUSTOM_WIDGETS[3])

        # Bouton change NATURE
        self.dlg.pushButtonRte2Chaussee.clicked.connect(self.torte2chaussee)
        self.dlg.pushButtonRte1Chaussee.clicked.connect(self.torte1chaussee)
        self.dlg.pushButtonEmpierree.clicked.connect(self.toempierree)
        self.dlg.pushButtonChemin.clicked.connect(self.tochemin)
        self.dlg.pushButtonSentier.clicked.connect(self.tosentier)
        self.dlg.pushButtonRondpoint.clicked.connect(self.torondpoint)

        # Bouton change nb voies
        self.dlg.pushButtonVoieSansObjet.clicked.connect(self.setvoieSansObj)
        self.dlg.pushButton1voie.clicked.connect(self.set1voie)
        self.dlg.pushButton2voies.clicked.connect(self.set2voies)
        self.dlg.pushButton3voies.clicked.connect(self.set3voies)

        # Bouton change largeur
        self.dlg.pushButtonLargeur14.clicked.connect(self.setLargeur14)
        self.dlg.pushButtonLargeur10.clicked.connect(self.setLargeur10)
        self.dlg.pushButtonLargeur7.clicked.connect(self.setLargeur7)
        self.dlg.pushButtonLargeur5.clicked.connect(self.setLargeur5)
        self.dlg.pushButtonLargeur3.clicked.connect(self.setLargeur3)
        self.dlg.pushButtonLargeurVide.clicked.connect(self.setLargeurVide)
        # evenement lineeditlargeur
        self.dlg.lineEditLargeur.mousePressEvent = self.click_edit
        self.dlg.lineEditLargeur.editingFinished.connect(self.editfocus)
        # self.dlg.lineEditLargeur.textEdited.connect(self.lineeditlargeur)
        self.dlg.lineEditLargeur.textChanged.connect(self.textchangelargeur)
        self.dlg.lineEditLargeur.editingFinished.connect(self.finedition)
        self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[2])


        # bouton importance
        self.dlg.pushButtonImportance1.clicked.connect(self.setImportance1)
        self.dlg.pushButtonImportance2.clicked.connect(self.setImportance2)
        self.dlg.pushButtonImportance3.clicked.connect(self.setImportance3)
        self.dlg.pushButtonImportance4.clicked.connect(self.setImportance4)
        self.dlg.pushButtonImportance5.clicked.connect(self.setImportance5)
        self.dlg.pushButtonImportance6.clicked.connect(self.setImportance6)

        # bouton sens
        self.dlg.pushButtonDoubleSens.clicked.connect(self.setDoubleSens)
        self.dlg.pushButtonSensUnique.clicked.connect(self.setSensUnique)
        self.dlg.pushButtonInverserSens.clicked.connect(self.setInverserSens)
        self.dlg.pushButtonSensSansObjet.clicked.connect(self.setSensSansObjet)
        self.dlg.pushButtonSensSansVal.clicked.connect(self.setSensSansValeur)

        # acces
        self.dlg.pushButtonAccesLibre.clicked.connect(self.setAccesLibre)
        self.dlg.pushButtonAccesRestreint.clicked.connect(self.setAccesRestreint)
        self.dlg.pushButtonAccesImpossible.clicked.connect(self.setAccesImpossible)


        # bouton d'actualisation de la selection
        # pour retrouver l'etat initial apres modif mais avant transaction
        self.dlg.pushButtonActualiseSelection.clicked.connect(self.actualiserSelection)
        self.dlg.pushButtonActualiseSelection.setEnabled(False)

        # bouton a propos de
        self.dlg.pushButtonAide.clicked.connect(self.afficheAProposeDe)

        # bouton chemin le plus court
        self.dlg.pushButtonchepluscourt.clicked.connect(self.runchepluscourt)

        # bouton afficher sens numerisation
        self.dlg.pushButtonsensNumerisation.clicked.connect(self.afficher_sens_num)

        # bouton "zoom sur la sélection"
        self.dlg.pushButtonZoom.clicked.connect(self.zoom_selection)

        # bouton valider la transaction
        self.dlg.pushButtonValiderTransaction.clicked.connect(self.validerLaTransaction)
        self.dlg.pushButtonValiderTransaction.setStyleSheet(CUSTOM_WIDGETS[4])

        self.dlg.setWindowFlags(Qt.WindowStaysOnTopHint)
        # show the dialog
        self.dlg.show()



        # Run the dialog event loop
        result = self.dlg.exec_()
        # # See if OK was pressed

        if result == 0:
            self.is_affiche_sens_num = False

        #     # Do something useful here - delete the line containing pass and
        #     # substitute with your code.
        #     pass
