# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ChangeAttributRoute
                                 A QGIS plugin
 Aide à la contribution directe sur le thème routier
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-01
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PÊCHEUR
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtGui import QValidator
from PyQt5.QtWidgets import QLineEdit, QWidget
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication,QRegExp
from qgis.PyQt.QtGui import QRegExpValidator
from qgis.PyQt.QtWidgets import QPushButton
from qgis._core import QgsMapLayer
from qgis.core import Qgis

# Import the code for the dialog
from .assistant_route_dialog import ChangeAttributRouteDialog
import os.path

from .modele import *
from .symbologie import *
from .fonction import *
from .cheminpluscourt import *
from .aproposde import Aproposde

# TODO : obsolete
# recuperation de l'id de la transaction (à partir du plugin espace co)
# def getidtransaction():
#     from qgis.utils import plugins
#     idtransaction = None
#     try:
#         processing_plugin = plugins[PLUGIN_ESPACE_CO]
#         print("espace co trouvé")
#         try:
#             idtransaction = processing_plugin.getlibelletransaction()
#         except AttributeError:
#             idtransaction = "Récuperation en cours de développement"
#     except KeyError:
#         print("espace co PAS trouvé")
#         pass
#
#     if idtransaction is None:
#         return "Pas de transaction vers la BDUNI (travail hors ligne)"
#     else:
#         return idtransaction


class ChangeAttributRoute:
    """QGIS Plugin Implementation."""

    def runchepluscourt(self):
        self.cheminpluscourt.cheminpluscourt()
        self.set_activeLayerRoute()
        # zoom sur la selection
        self.iface.actionZoomToSelected().trigger()

    # NATURE *******************************************************
    def commut_nature(self, nature_val, button_name):
        if self.get_nb_selection() == 0:
            return

        self.ismodifie = True
        current_val = self.dico_attributs_commun.get(NATURE)

        btn = getattr(self.dlg, button_name)
        valider_btn = self.dlg.pushButtonValiderTransaction
        actualise_btn = self.dlg.pushButtonActualiseSelection

        if current_val == nature_val:
            valider_btn.setEnabled(False)
            actualise_btn.setEnabled(False)
            btn.setStyleSheet(CUSTOM_WIDGETS[1])
            self.dico_attributs_modifie.pop(NATURE, None)

            if len(self.dico_attributs_modifie) == 0:
                valider_btn.setEnabled(False)
        else:
            btn.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[NATURE] = nature_val
            valider_btn.setEnabled(True)
            actualise_btn.setEnabled(True)

        self.controleDonnees(nature_val)
        self.set_attributs_defaut(nature_val)
        self.initbtnclic(LIST_BTN_NATURE, button_name)

    def torte2chaussee(self):
        self.commut_nature(RTE_2_CHAUSSEES, "pushButtonRte2Chaussee")

    def torte1chaussee(self):
        self.commut_nature(RTE_1_CHAUSSEE, "pushButtonRte1Chaussee")

    def toempierree(self):
        self.commut_nature(RTE_EMPIERREE, "pushButtonEmpierree")

    def tochemin(self):
        self.commut_nature(CHEMIN, "pushButtonChemin")

    def tosentier(self):
        self.commut_nature(SENTIER, "pushButtonSentier")

    def torondpoint(self):
        self.commut_nature(ROND_POINT, "pushButtonRondpoint")
    # NATURE *******************************************************

    # IMPORTANCE ***************************************************
    def setImportance(self, niveau):
        if self.get_nb_selection() == 0:
            return

        self.ismodifie = True
        btn_name = f"pushButtonImportance{niveau}"
        btn = getattr(self.dlg, btn_name)
        self.initbtnclic(LIST_BTN_IMPORTANCE, btn_name)

        if self.dico_attributs_commun.get(IMPORTANCE) == str(niveau):
            btn.setStyleSheet(CUSTOM_WIDGETS[1])
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)

            self.dico_attributs_modifie.pop(IMPORTANCE, None)

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            btn.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[IMPORTANCE] = str(niveau)
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)

            if niveau == 6:
                self.set_attributs_defaut(IMPORTANCE)

    def setImportance1(self):
        self.setImportance(1)

    def setImportance2(self):
        self.setImportance(2)

    def setImportance3(self):
        self.setImportance(3)

    def setImportance4(self):
        self.setImportance(4)

    def setImportance5(self):
        self.setImportance(5)

    def setImportance6(self):
        self.setImportance(6)
    # IMPORTANCE ***************************************************


    # VOIES ********************************************************
    def set_voie(self, valeur, nom_bouton):
        if self.get_nb_selection() == 0:
            return

        self.ismodifie = True
        self.initbtnclic(LIST_BTN_NBVOIES, nom_bouton)

        bouton = getattr(self.dlg, nom_bouton)
        valeur_actuelle = self.dico_attributs_commun[NB_VOIES]

        if valeur_actuelle == valeur:
            bouton.setStyleSheet(CUSTOM_WIDGETS[1])
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            try:
                del self.dico_attributs_modifie[NB_VOIES]
            except KeyError:
                pass

            if not self.dico_attributs_modifie:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            bouton.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[NB_VOIES] = valeur

    def setvoieSansObj(self):
        self.set_voie(SANS_OBJET, "pushButtonVoieSansObjet")

    def set1voie(self):
        self.set_voie("1", "pushButton1voie")

    def set2voies(self):
        self.set_voie("2", "pushButton2voies")

    def set3voies(self):
        self.set_voie("3", "pushButton3voies")

    # VOIES ********************************************************

    # SENS *********************************************************
    def setSens(self,valeur,nom_btn):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(LIST_BTN_SENS, nom_btn)
        bouton = getattr(self.dlg, nom_btn)
        if self.dico_attributs_commun[SENS] == valeur:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            bouton.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[SENS]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            bouton.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[SENS] = valeur

    def setDoubleSens(self):
        self.setSens(DOUBLE_SENS, "pushButtonDoubleSens")

    def setSensSansObjet(self):
        self.setSens(SANS_OBJET, "pushButtonSensSansObjet")

    # TODO : pas dans les specs
    # def setSensSansValeur(self):
    #     self.setSens("","pushButtonSensSansVal")




    def setSensUnique(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(LIST_BTN_SENS, "pushButtonSensUnique")
        # if self.dico_attributs_commun[SENS] == SENS_DIRECT or self.dico_attributs_commun[SENS] == SENS_INVERSE:
        if self.dico_attributs_commun[SENS] == SENS_UNIQUE \
                or self.dico_attributs_commun[SENS] == SENS_DIRECT\
                or self.dico_attributs_commun[SENS] == SENS_INVERSE:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            self.dlg.pushButtonSensUnique.setStyleSheet(CUSTOM_WIDGETS[1])
            try:
                del self.dico_attributs_modifie[SENS]
            except KeyError:
                pass

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            self.dlg.pushButtonSensUnique.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)
            self.dico_attributs_modifie[SENS] = SENS_DIRECT

    def setInverserSens(self):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(LIST_BTN_SENS, "pushButtonInverserSens")
        # si sens direct on change en sens inverse et inversement
        idchamps = self.layer.fields().indexFromName(SENS)
        # self.layer.startEditing()
        for selection in self.listeSelection:
            attr = selection.attributes()
            sens = attr[idchamps]
            if sens == SENS_DIRECT:
                self.dico_attributs_modifie[SENS] = SENS_INVERSE
            elif sens == SENS_INVERSE:
                self.dico_attributs_modifie[SENS] = SENS_DIRECT
            else:
                afficheerreur("Ce tronçon n'est pas en sens unique, il ne sera pas modifié")
                self.dlg.pushButtonInverserSens.setStyleSheet(CUSTOM_WIDGETS[2])
                return

        self.dlg.pushButtonInverserSens.setStyleSheet(CUSTOM_WIDGETS[0])
        self.dlg.pushButtonValiderTransaction.setEnabled(True)
        self.dlg.pushButtonActualiseSelection.setEnabled(True)

    # TODO pas dans les specs
    # def setSensSansValeur(self):
    #     if self.get_nb_selection() == 0:
    #         return
    #     self.ismodifie = True
    #     self.initbtnclic(LIST_BTN_SENS, "pushButtonSensSansVal")
    #     if self.dico_attributs_commun[SENS] == "":
    #         self.dlg.pushButtonValiderTransaction.setEnabled(False)
    #         self.dlg.pushButtonActualiseSelection.setEnabled(False)
    #         self.dlg.pushButtonSensSansVal.setStyleSheet(CUSTOM_WIDGETS[1])
    #         try:
    #             del self.dico_attributs_modifie[SENS]
    #         except KeyError:
    #             pass
    #
    #         if len(self.dico_attributs_modifie) == 0:
    #             self.dlg.pushButtonValiderTransaction.setEnabled(False)
    #     else:
    #         self.dlg.pushButtonSensSansVal.setStyleSheet(CUSTOM_WIDGETS[0])
    #         self.dico_attributs_modifie[SENS] = ""
    #         self.dlg.pushButtonValiderTransaction.setEnabled(True)
    #         self.dlg.pushButtonActualiseSelection.setEnabled(True)

    # ACCES ************************************************************
    def set_acces(self, valeur_cible, bouton_name):
        if self.get_nb_selection() == 0:
            return
        self.ismodifie = True
        self.initbtnclic(LIST_BTN_ACCES, bouton_name)

        current_val = self.dico_attributs_commun.get(ACCES)
        bouton = getattr(self.dlg, bouton_name)

        if current_val == valeur_cible:
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            self.dlg.pushButtonActualiseSelection.setEnabled(False)
            bouton.setStyleSheet(CUSTOM_WIDGETS[1])
            self.dico_attributs_modifie.pop(ACCES, None)

            if len(self.dico_attributs_modifie) == 0:
                self.dlg.pushButtonValiderTransaction.setEnabled(False)
        else:
            if valeur_cible == ACCES_IMPOSSIBLE:
                self.set_attributs_defaut(ACCES_IMPOSSIBLE)

            bouton.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dico_attributs_modifie[ACCES] = valeur_cible
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            self.dlg.pushButtonActualiseSelection.setEnabled(True)

    def setAccesLibre(self):
        self.set_acces(ACCES_LIBRE, "pushButtonAccesLibre")

    def setAccesRestreint(self):
        self.set_acces(ACCES_RESTREINT, "pushButtonAccesRestreint")

    def setAccesImpossible(self):
        self.set_acces(ACCES_IMPOSSIBLE, "pushButtonAccesImpossible")
    # ACCES ************************************************************


    def get_nb_selection(self):
        return self.layer.selectedFeatureCount()

    def __init__(self, iface):
        # TODO __init__
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """

        # declaration :dialogue

        self.dlgAProposDe = None
        self.dlg = None

        # boolean pour afficher/masquer le sens de numérisation
        self.is_affiche_sens_num = False

        self.read_only_nature = False
        self.champs_manquant = []
        self.read_only_nb_voies = False
        self.read_only_larg_chaussee = False
        self.read_only_importance = False
        self.read_only_sens_circu = False
        self.read_only_acces_leger = False
        # ici je gere toutes les restrictions ensemble, à voir si plus tard on les sépare
        self.read_only_restriction = False
        self.read_only_restr_hauteur = False
        self.read_only_restr_largeur = False
        self.read_only_restr_longueur = False
        self.read_only_restr_poids_essieu = False
        self.read_only_restr_poids_total = False

        self.ismodifie = False

        self.listBtnTotal = []
        self.listBtnTotal = LIST_BTN_NATURE.copy()
        self.listBtnTotal += LIST_BTN_NBVOIES.copy()
        self.listBtnTotal += ["lineEditLargeur"]
        self.listBtnTotal += LIST_BTN_IMPORTANCE.copy()
        self.listBtnTotal += LIST_BTN_SENS.copy()
        self.listBtnTotal += LIST_BTN_ACCES.copy()
        self.listBtnTotal += LIST_LINEEDIT_RESTR.copy()

        # construction d'un dico (cle : btn, valeur, regex)
        # pour gerer la validation du format des données juste avant la transaction
        self.dict_widg_reggex = {
                "lineEditLargeur": REGEX_LARGEUR,
                "lineEditRestrHauteur": REGEX_RESTR_HAUTEUR,
                "lineEditRestrLargeur": REGEX_RESTR_LARGEUR,
                "lineEditRestrLongueur": REGEX_RESTR_LONGUEUR,
                "lineEditRestrPoidsEssieu": REGEX_RESTR_POIDS_ESSIEU,
                "lineEditRestrPoidsTotal": REGEX_RESTR_POIDS_TOTAL
            }


        self.iface = iface
        # Save reference to the QGIS interface
        self.layer = None

        self.cheminpluscourt = None

        self.listeSelection = None

        # dictionnaire pour gérer les attributs de la selection
        # clé = identifiant
        self.dico_attributs_selection = {}

        # dico des attributs commun
        self.dico_attributs_commun = {}

        # dico des boutons correspondant aux attributs commun
        # pour garder l'aspect initial des boutons dans l'interfac
        self.dico_btn_initial = {}

        # dico pour stocker les attributs modifiés
        self.dico_attributs_modifie = {}

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ChangeAttributRoute_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator(self)
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

    # initialise la liste de tous les boutons (des differents champs)
    # excepté ceux qui sont en lecture seule
    def get_bouton_total_editable(self):
        list_btn = []
        if not self.read_only_nature:
            list_btn += LIST_BTN_NATURE.copy()
        if not self.read_only_larg_chaussee:
            list_btn += LIST_BTN_LARGEUR.copy()
        if not self.read_only_nb_voies:
            list_btn += LIST_BTN_NBVOIES.copy()
        # self.listBtnTotal += ["lineEditLargeur"]
        if not self.read_only_importance:
            list_btn += LIST_BTN_IMPORTANCE.copy()
        if not self.read_only_sens_circu:
            list_btn += LIST_BTN_SENS.copy()
        if not self.read_only_acces_leger:
            list_btn += LIST_BTN_ACCES.copy()
        if not self.read_only_restriction:
            list_btn += LIST_LINEEDIT_RESTR.copy()
        return list_btn


    # met en rose les attributs par défauts en fonction de la nature
    def set_attributs_defaut(self,attribut):
        # TODO set_attributs_defaut
        self.initbtnclic(self.listBtnTotal)

        if attribut == RTE_2_CHAUSSEES:
            if not self.read_only_sens_circu:
                self.dlg.pushButtonSensUnique.setStyleSheet(CUSTOM_WIDGETS[0])
                self.dico_attributs_modifie[SENS] = SENS_DIRECT

        if attribut == RTE_EMPIERREE or attribut == CHEMIN:
            if not self.read_only_nb_voies:
                self.dico_attributs_modifie[NB_VOIES] = SANS_OBJET
                self.dlg.pushButtonVoieSansObjet.setStyleSheet(CUSTOM_WIDGETS[0])
            # self.dlg.pushButtonLargeurVide.setStyleSheet(CUSTOM_WIDGETS[0])

            if not self.read_only_larg_chaussee:
                self.dico_attributs_modifie[LARGEUR] = "NULL"
                # on passe l'edit largeur en blanc aussi
                self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[2])

            if not self.read_only_importance:
                self.dico_attributs_modifie[IMPORTANCE] = "5"
                self.dlg.pushButtonImportance5.setStyleSheet(CUSTOM_WIDGETS[0])

            if not self.read_only_sens_circu:
                self.dlg.pushButtonDoubleSens.setStyleSheet(CUSTOM_WIDGETS[0])
                self.dico_attributs_modifie[SENS] = DOUBLE_SENS

        if attribut == SENTIER:
            if not self.read_only_nb_voies:
                self.dico_attributs_modifie[NB_VOIES] = SANS_OBJET
                self.dlg.pushButtonVoieSansObjet.setStyleSheet(CUSTOM_WIDGETS[0])

            if not self.read_only_larg_chaussee:
                # self.dlg.pushButtonLargeurVide.setStyleSheet(CUSTOM_WIDGETS[0])
                self.dico_attributs_modifie[LARGEUR] = "NULL"
                # on passe l'edit largeur en blanc aussi
                self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[2])

            # self.dlg.pushButtonImportance6.setStyleSheet(CUSTOM_WIDGETS[0])
            if not self.read_only_importance:
                self.dico_attributs_modifie[IMPORTANCE] = "6"
                self.dlg.pushButtonImportance6.setStyleSheet(CUSTOM_WIDGETS[0])

            if not self.read_only_sens_circu:
                self.dlg.pushButtonSensSansObjet.setStyleSheet(CUSTOM_WIDGETS[0])
                self.dico_attributs_modifie[SENS] = SANS_OBJET

            if not self.read_only_acces_leger:
                self.dlg.pushButtonAccesImpossible.setStyleSheet(CUSTOM_WIDGETS[0])
                self.dico_attributs_modifie[ACCES] = ACCES_IMPOSSIBLE

        if attribut == ROND_POINT:
            if not self.read_only_sens_circu:
                self.dlg.pushButtonSensUnique.setStyleSheet(CUSTOM_WIDGETS[0])
                self.dico_attributs_modifie[SENS] = SENS_DIRECT

        # if attribut == ACCES_IMPOSSIBLE:
        #     self.dlg.pushButtonImportance6.setStyleSheet(CUSTOM_WIDGETS[0])
        #     self.dico_attributs_modifie[IMPORTANCE] = "6"
        #
        # if attribut == IMPORTANCE:
        #     if self.dico_attributs_commun[NATURE] == RTE_1_CHAUSSEE:
        #         self.dlg.pushButtonSensSansVal.setStyleSheet(CUSTOM_WIDGETS[0])
        #         self.dico_attributs_modifie[SENS] = ""


    def set_attributs_commun_lineedit(self,nom_attr, liste_valeurs, nom_widget_lineedit):
        """
        Gère l'affichage et le stockage des valeurs communes ou multiples.
        """
        if len(set(liste_valeurs)) != 1:
            valeur = "***"
        else:
            valeur = liste_valeurs[0]

        # Stockage dans les dictionnaires
        self.dico_attributs_commun[nom_attr] = valeur
        self.dico_btn_initial[nom_attr] = nom_widget_lineedit if valeur != "***" else "***"

        # Mise à jour du champ LineEdit
        widget = getattr(self.dlg, nom_widget_lineedit, None)
        if widget:
            widget.setText(str(valeur))


    # rempli un dico avec uniquement les attributs communs
    # sinon "***" à la place des attributs non communs
    def set_attributs_commun(self):
        # TODO set_attributs_commun

        cleabs_selection = []
        nature_selection = []
        nbvoies_selection = []
        largeur_selection = []
        importance_selection = []
        sens_selection = []
        acces_selection = []
        restriction_hauteur = []
        restriction_largeur = []
        restriction_longueur = []
        restriction_poids_essieu = []
        restriction_poids_total = []
        # chaque liste contient tous les attributs correspondant au champ choisi
        # avec doublons éventuel
        for cle,valeur in self.dico_attributs_selection.items():
            cleabs_selection.append(valeur[0])
            nature_selection.append(valeur[1])
            nbvoies_selection.append(valeur[2])
            largeur_selection.append(valeur[3])
            importance_selection.append(valeur[4])
            sens_selection.append(valeur[5])
            acces_selection.append(valeur[6])
            restriction_hauteur.append(valeur[7])
            restriction_largeur.append(valeur[8])
            restriction_longueur.append(valeur[9])
            restriction_poids_essieu.append(valeur[10])
            restriction_poids_total.append(valeur[11])


        # set : list des attributs UNIQUE
        # len, renvoi la taille, donc si renvoi 1 = un champ commun
        # ....._selection : liste contenant tous les attributs de chaque entité sélectionnés
        # NATURE
        if len(set(nature_selection)) != 1:
            self.dico_attributs_commun[NATURE] = "***"
            self.dico_btn_initial[NATURE] = "***"
        else:
            self.dico_attributs_commun[NATURE] = nature_selection[0]
            if nature_selection[0] == RTE_2_CHAUSSEES:
                self.dico_btn_initial[NATURE] = "pushButtonRte2Chaussee"
            if nature_selection[0] == RTE_1_CHAUSSEE:
                self.dico_btn_initial[NATURE] = "pushButtonRte1Chaussee"
            if nature_selection[0] == RTE_EMPIERREE:
                self.dico_btn_initial[NATURE] = "pushButtonEmpierree"
            if nature_selection[0] == CHEMIN:
                self.dico_btn_initial[NATURE] = "pushButtonChemin"
            if nature_selection[0] == SENTIER:
                self.dico_btn_initial[NATURE] = "pushButtonSentier"
            if nature_selection[0] == ROND_POINT:
                self.dico_btn_initial[NATURE] = "pushButtonRondpoint"
        # NBVOIES
        if len(set(nbvoies_selection)) != 1:
            self.dico_attributs_commun[NB_VOIES] = "***"
            self.dico_btn_initial[NB_VOIES] = "***"
        else:
            self.dico_attributs_commun[NB_VOIES] = nbvoies_selection[0]
            if nbvoies_selection[0] == "3":
                self.dico_btn_initial[NB_VOIES] = "pushButton3voies"
            if nbvoies_selection[0] == "2":
                self.dico_btn_initial[NB_VOIES] = "pushButton2voies"
            if nbvoies_selection[0] == "1":
                self.dico_btn_initial[NB_VOIES] = "pushButton1voie"
            if nbvoies_selection[0] == SANS_OBJET:
                self.dico_btn_initial[NB_VOIES] = "pushButtonVoieSansObjet"

        # on traite les attributs communs pour les lineedit
        # LARGEUR
        self.set_attributs_commun_lineedit(LARGEUR, largeur_selection, "lineEditLargeur")
        # RESTRICTION HAUTEUR
        self.set_attributs_commun_lineedit(RESTRICTION_HAUTEUR, restriction_hauteur, "lineEditRestrHauteur")
        # RESTRICTION HAUTEUR
        self.set_attributs_commun_lineedit(RESTRICTION_LARGEUR, restriction_largeur, "lineEditRestrLargeur")
        # RESTRICTION HAUTEUR
        self.set_attributs_commun_lineedit(RESTRICTION_LONGUEUR, restriction_longueur, "lineEditRestrLongueur")
        # RESTRICTION HAUTEUR
        self.set_attributs_commun_lineedit(RESTRICTION_POIDS_ESSIEU, restriction_poids_essieu, "lineEditRestrPoidsEssieu")
        # RESTRICTION HAUTEUR
        self.set_attributs_commun_lineedit(RESTRICTION_POIDS_TOTAL, restriction_poids_total, "lineEditRestrPoidsTotal")

        # IMPORTANCE
        if len(set(importance_selection)) != 1:
            self.dico_attributs_commun[IMPORTANCE] = "***"
            self.dico_btn_initial[IMPORTANCE] = "***"
        else:
            self.dico_attributs_commun[IMPORTANCE] = importance_selection[0]
            if importance_selection[0] == "1":
                self.dico_btn_initial[IMPORTANCE] = "pushButtonImportance1"
            if importance_selection[0] == "2":
                self.dico_btn_initial[IMPORTANCE] = "pushButtonImportance2"
            if importance_selection[0] == "3":
                self.dico_btn_initial[IMPORTANCE] = "pushButtonImportance3"
            if importance_selection[0] == "4":
                self.dico_btn_initial[IMPORTANCE] = "pushButtonImportance4"
            if importance_selection[0] == "5":
                self.dico_btn_initial[IMPORTANCE] = "pushButtonImportance5"
            if importance_selection[0] == "6":
                self.dico_btn_initial[IMPORTANCE] = "pushButtonImportance6"

        # SENS
        # different ici, car sens direct OU sens inverse c'est pareil
        nb_sens_unique = sens_selection.count(SENS_DIRECT) + sens_selection.count(SENS_INVERSE)
        # que des sens directs ou sens inverse
        if self.get_nb_selection() != 0 and (nb_sens_unique == len(sens_selection)):
            self.dico_attributs_commun[SENS] = SENS_UNIQUE
            self.dico_btn_initial[SENS] = "pushButtonSensUnique"
            # pas de valeurs communes
        elif len(set(sens_selection)) != 1:
            self.dico_attributs_commun[SENS] = "***"
            self.dico_btn_initial[SENS] = "***"
        else:
            self.dico_attributs_commun[SENS] = sens_selection[0]
            if sens_selection[0] == DOUBLE_SENS:
                self.dico_btn_initial[SENS] = "pushButtonDoubleSens"
            if sens_selection[0] == SANS_OBJET:
                self.dico_btn_initial[SENS] = "pushButtonSensSansObjet"
            if sens_selection[0] == "":
                self.dico_btn_initial[SENS] = "pushButtonSensSansVal"

        # ACCES
        if len(set(acces_selection)) != 1:
            self.dico_attributs_commun[ACCES] = "***"
            self.dico_btn_initial[ACCES] = "***"
        else:
            self.dico_attributs_commun[ACCES] = acces_selection[0]
            if acces_selection[0] == ACCES_LIBRE:
                self.dico_btn_initial[ACCES] = "pushButtonAccesLibre"
            if acces_selection[0] == ACCES_RESTREINT:
                self.dico_btn_initial[ACCES] = "pushButtonAccesRestreint"
            if acces_selection[0] == ACCES_IMPOSSIBLE:
                self.dico_btn_initial[ACCES] = "pushButtonAccesImpossible"

        # les attributs communs seront renseignés, les autres auront "***".
        return self.dico_attributs_commun

    # exemple : transforme 4.0 en 4, mais garde 4.5
    # garde "NULL"
    def format_nombre_lineedit(self,number):
        # si "number" vaut "NULL" on garde tel quel
        if isinstance(number, str) and number.upper() == "NULL":
            return number
        try:
            num = float(number)
        except:
            return number
        if int(num) == num:
            return str(int(num))
        else:
            return number

    """**********************************
    définir un dictionnaire d'attributs
    clé : identifiant des entités
    valeurs : attributs
    *************************************"""
    def set_attributs_selection(self):
        # TODO set_attributs_selection
        idcleabs = self.layer.fields().indexFromName(CLEABS)
        idnature = self.layer.fields().indexFromName(NATURE)
        idnbvoies = self.layer.fields().indexFromName(NB_VOIES)
        idlargeur = self.layer.fields().indexFromName(LARGEUR)
        idimportance = self.layer.fields().indexFromName(IMPORTANCE)
        idsens = self.layer.fields().indexFromName(SENS)
        idacces = self.layer.fields().indexFromName(ACCES)
        idrestrhauteur = self.layer.fields().indexFromName(RESTRICTION_HAUTEUR)
        idrestrlargeur = self.layer.fields().indexFromName(RESTRICTION_LARGEUR)
        idrestrlongueur = self.layer.fields().indexFromName(RESTRICTION_LONGUEUR)
        idrestrpoidsessieu = self.layer.fields().indexFromName(RESTRICTION_POIDS_ESSIEU)
        idrestroidstotal = self.layer.fields().indexFromName(RESTRICTION_POIDS_TOTAL)

        self.dico_attributs_selection.clear()
        for entite in self.listeSelection:
            attr = entite.attributes()

            ident = entite.id()
            self.dico_attributs_selection[ident] = [attr[idcleabs],
                        attr[idnature],
                        attr[idnbvoies],
                        self.format_nombre_lineedit(attr[idlargeur]),
                        attr[idimportance],
                        attr[idsens],
                        attr[idacces],
                        self.format_nombre_lineedit(attr[idrestrhauteur]),
                        self.format_nombre_lineedit(attr[idrestrlargeur]),
                        self.format_nombre_lineedit(attr[idrestrlongueur]),
                        self.format_nombre_lineedit(attr[idrestrpoidsessieu]),
                        self.format_nombre_lineedit(attr[idrestroidstotal])]
        return self.dico_attributs_selection

    def set_activeLayerRoute(self,message = True):
        # TODO set_activeLayerRoute
        project = QgsProject.instance()
        layer = project.mapLayersByName(LAYER_ROUTE)
        if not layer:
            if message:
                afficheerreur(f"la couche \"{LAYER_ROUTE}\" n'existe pas",TITRE_INTERFACE)
            return False
        else:
            self.iface.setActiveLayer(layer[0])
            self.layer = self.iface.activeLayer()
            return True

    # initialiser les boutons en rose lorsqu'ils sont pressés
    # passe tous les boutons d'un groupe (listgroupebtn) par defaut avant de mettre en rose celui en parametre (btnclick)
    def initbtnclic(self, listgroupebtn, btnclick=""):
        # TODO initbtnclic

        # en rose le cliqué, tous les autres d'un même groupe par defaut.
        widgets = self.dlg.findChildren((QPushButton, QLineEdit))
        for widget in widgets:
            name = widget.objectName()
            # Filtrer uniquement les noms présents dans listgroupebtn
            if name in listgroupebtn:
                # Appliquer le style de base (fond neutre)
                widget.setStyleSheet(CUSTOM_WIDGETS[2])
                # Si c'est le widget cliqué, appliquer le style (fond rose)
                if name == btnclick:
                    widget.setStyleSheet(CUSTOM_WIDGETS[0])

        # garder en "vert" les boutons initiaux QPushbutton
        # et avec valeur "***" pour les QLineEdit
        for attribut in self.dico_btn_initial.values():
            btn = self.dlg.findChild(QWidget,attribut)
            if btn is not None:
                if attribut != "***":
                    btn.setStyleSheet(CUSTOM_WIDGETS[1])


    def get_bouton_nature_actif(self):
        # TODO get_bouton_nature_actif
        nature = None
        for val in self.dico_attributs_selection.values():
            nature =  val[1]
        return nature


    # désactive les widgets pour les valeurs interdites
    def controleDonnees(self, nature):
        # TODO controleDonnees

        # active tous les boutons initialement
        self.activerBoutons(True)

        if nature == RTE_2_CHAUSSEES:
            if not self.read_only_importance:
                self.dlg.pushButtonImportance6.setEnabled(False)
                self.dlg.pushButtonImportance6.setStyleSheet(CUSTOM_WIDGETS[6])
            if not self.read_only_nb_voies:
                self.dlg.pushButtonVoieSansObjet.setEnabled(False)
                self.dlg.pushButtonVoieSansObjet.setStyleSheet(CUSTOM_WIDGETS[6])
            if not self.read_only_sens_circu:
                self.dlg.pushButtonInverserSens.setEnabled(False)
                self.dlg.pushButtonInverserSens.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonSensSansObjet.setEnabled(False)
                self.dlg.pushButtonSensSansObjet.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonDoubleSens.setEnabled(False)
                self.dlg.pushButtonDoubleSens.setStyleSheet(CUSTOM_WIDGETS[6])
        if nature == RTE_1_CHAUSSEE:
            if not self.read_only_nb_voies:
                self.dlg.pushButtonVoieSansObjet.setEnabled(False)
                self.dlg.pushButtonVoieSansObjet.setStyleSheet(CUSTOM_WIDGETS[6])

        if nature == RTE_EMPIERREE:
            if not self.read_only_sens_circu:
                self.dlg.pushButtonSensUnique.setEnabled(False)
                self.dlg.pushButtonSensUnique.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonInverserSens.setEnabled(False)
                self.dlg.pushButtonInverserSens.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonSensSansObjet.setEnabled(False)
                self.dlg.pushButtonSensSansObjet.setStyleSheet(CUSTOM_WIDGETS[6])
            if not self.read_only_nb_voies:
                self.dlg.pushButton1voie.setEnabled(False)
                self.dlg.pushButton1voie.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButton2voies.setEnabled(False)
                self.dlg.pushButton2voies.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButton3voies.setEnabled(False)
                self.dlg.pushButton3voies.setStyleSheet(CUSTOM_WIDGETS[6])
            if not self.read_only_larg_chaussee:
                self.dlg.lineEditLargeur.setEnabled(False)
                self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[6])
            if not self.read_only_importance:
                self.dlg.pushButtonImportance1.setEnabled(False)
                self.dlg.pushButtonImportance1.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonImportance2.setEnabled(False)
                self.dlg.pushButtonImportance2.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonImportance3.setEnabled(False)
                self.dlg.pushButtonImportance3.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonImportance4.setEnabled(False)
                self.dlg.pushButtonImportance4.setStyleSheet(CUSTOM_WIDGETS[6])

        if nature == CHEMIN:
            if not self.read_only_sens_circu:
                self.dlg.pushButtonSensUnique.setEnabled(False)
                self.dlg.pushButtonSensUnique.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonInverserSens.setEnabled(False)
                self.dlg.pushButtonInverserSens.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonSensSansObjet.setEnabled(False)
                self.dlg.pushButtonSensSansObjet.setStyleSheet(CUSTOM_WIDGETS[6])
            if not self.read_only_nb_voies:
                self.dlg.pushButton1voie.setEnabled(False)
                self.dlg.pushButton1voie.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButton2voies.setEnabled(False)
                self.dlg.pushButton2voies.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButton3voies.setEnabled(False)
                self.dlg.pushButton3voies.setStyleSheet(CUSTOM_WIDGETS[6])
            if not self.read_only_larg_chaussee:
                self.dlg.lineEditLargeur.setEnabled(False)
                self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[6])
            if not self.read_only_importance:
                self.dlg.pushButtonImportance1.setEnabled(False)
                self.dlg.pushButtonImportance1.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonImportance2.setEnabled(False)
                self.dlg.pushButtonImportance2.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonImportance3.setEnabled(False)
                self.dlg.pushButtonImportance3.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonImportance4.setEnabled(False)
                self.dlg.pushButtonImportance4.setStyleSheet(CUSTOM_WIDGETS[6])

        if nature == SENTIER:
            if not self.read_only_sens_circu:
                self.dlg.pushButtonDoubleSens.setEnabled(False)
                self.dlg.pushButtonDoubleSens.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonSensUnique.setEnabled(False)
                self.dlg.pushButtonSensUnique.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonInverserSens.setEnabled(False)
                self.dlg.pushButtonInverserSens.setStyleSheet(CUSTOM_WIDGETS[6])
            if not self.read_only_larg_chaussee:
                self.dlg.lineEditLargeur.setEnabled(False)
                self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[6])
            if not self.read_only_acces_leger:
                self.dlg.pushButtonAccesLibre.setEnabled(False)
                self.dlg.pushButtonAccesLibre.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonAccesRestreint.setEnabled(False)
                self.dlg.pushButtonAccesRestreint.setStyleSheet(CUSTOM_WIDGETS[6])
            if not self.read_only_importance:
                self.dlg.pushButtonImportance1.setEnabled(False)
                self.dlg.pushButtonImportance1.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonImportance2.setEnabled(False)
                self.dlg.pushButtonImportance2.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonImportance3.setEnabled(False)
                self.dlg.pushButtonImportance3.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonImportance4.setEnabled(False)
                self.dlg.pushButtonImportance4.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonImportance5.setEnabled(False)
                self.dlg.pushButtonImportance5.setStyleSheet(CUSTOM_WIDGETS[6])
            if not self.read_only_nb_voies:
                self.dlg.pushButton1voie.setEnabled(False)
                self.dlg.pushButton1voie.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButton2voies.setEnabled(False)
                self.dlg.pushButton2voies.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButton3voies.setEnabled(False)
                self.dlg.pushButton3voies.setStyleSheet(CUSTOM_WIDGETS[6])

        if nature == ROND_POINT:
            if not self.read_only_importance:
                self.dlg.pushButtonImportance6.setEnabled(False)
                self.dlg.pushButtonImportance6.setStyleSheet(CUSTOM_WIDGETS[6])
            if not self.read_only_nb_voies:
                self.dlg.pushButtonVoieSansObjet.setEnabled(False)
                self.dlg.pushButtonVoieSansObjet.setStyleSheet(CUSTOM_WIDGETS[6])
            if not self.read_only_sens_circu:
                self.dlg.pushButtonDoubleSens.setEnabled(False)
                self.dlg.pushButtonDoubleSens.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonSensSansObjet.setEnabled(False)
                self.dlg.pushButtonSensSansObjet.setStyleSheet(CUSTOM_WIDGETS[6])
                self.dlg.pushButtonInverserSens.setEnabled(False)
                self.dlg.pushButtonInverserSens.setStyleSheet(CUSTOM_WIDGETS[6])

    def activerBoutons(self, affiche):
        list_btn_editable = self.get_bouton_total_editable()

        # champ en lecture seul
        widgets = self.dlg.findChildren((QPushButton, QLineEdit))
        for widget in widgets:
            name = widget.objectName()
            if affiche:
                if name in list_btn_editable:
                    # désactive ou nom les btn
                    widget.setEnabled(affiche)
            else:
                if name in self.listBtnTotal:
                    # désactive ou nom les btn
                    widget.setEnabled(affiche)

        self.disable_btn_champ_manquant()

    # désactive les btn dont les champs sont manquants
    def disable_btn_champ_manquant(self):
        # print(self.champs_manquant)
        widgets = self.dlg.findChildren((QPushButton, QLineEdit))
        for widget in widgets:
            for champ_absent in self.champs_manquant:
                if champ_absent in DICO_CHAMP_BTN.keys():
                    if widget.objectName() in DICO_CHAMP_BTN[champ_absent]:
                        if type(widget) == QLineEdit:
                            widget.setText("")
                        widget.setEnabled(False)


    # retourne la valeur du champ par defaut OU modifié
    def get_valeur_from_champs(self,nature):
        if self.dico_attributs_modifie.get(nature) is None:
            return self.dico_attributs_commun.get(nature)
        else:
            return self.dico_attributs_modifie.get(nature)


    def test_valeur_valide(self):

        str_erreur = ""

        # TEST SUR champs commun a :RTE_2_CHAUSSEE et RTE_1_CHAUSSEE
        if (self.dico_attributs_modifie.get(NATURE) == RTE_2_CHAUSSEES or
            self.dico_attributs_modifie.get(NATURE) == RTE_1_CHAUSSEE):
            # test sur le nombre de voies
            if (self.get_valeur_from_champs(NB_VOIES) == SANS_OBJET or
                    self.get_valeur_from_champs(NB_VOIES) is None or
                    self.get_valeur_from_champs(NB_VOIES) == "***"):
                str_erreur += "Veuillez renseigner un nombre de voies\n"
            # test sur largeur
            if (self.get_valeur_from_champs(LARGEUR) == "NULL" or
                    self.get_valeur_from_champs(LARGEUR) == "***"):
                str_erreur += "Veuillez renseigner une largeur de chaussée\n"
        #  TEST en plus sur RTE_2_CHAUSSEE
        #     test sur l'importance
            if self.get_valeur_from_champs(IMPORTANCE) == "6":
                str_erreur = "Veuillez renseigner une importance différente de 6"

        # TEST SUR champs :ROND_POINT
        if self.dico_attributs_modifie.get(NATURE) == ROND_POINT:
            # test sur le nombre de voies
            if (self.get_valeur_from_champs(NB_VOIES) == SANS_OBJET or
                    self.get_valeur_from_champs(NB_VOIES) is None or
                    self.get_valeur_from_champs(NB_VOIES) == "***"):
                str_erreur += "Veuillez renseigner un nombre de voies\n"
            # test sur largeur
            if (self.get_valeur_from_champs(LARGEUR) == "NULL" or
                    self.get_valeur_from_champs(LARGEUR) == "***"):
                str_erreur += "Veuillez renseigner une largeur de chaussée\n"

        if str_erreur != "":
            afficheerreur(str_erreur)
            return False
        else:
            return True

    def afficheMessageBar(self, message):
        self.iface.messageBar().pushMessage("Info", message, level=Qgis.Info, duration=5)

    def colorchange(self):
        self.actualiserSelection()

    # test si un attribut modifié est deja dans les attributs de la selection
    def modifie_isin_selection(self,attribut):
        # TODO modifie_isin_selection
        for sel in self.dico_attributs_selection.values():
            if attribut == sel[1]:
                return True
            else:
                return False

    def validerLaTransaction(self):
        # tester les valeurs possibles ou interdites en fonction de la nature
        # return false si les valeurs ne sont pas valides
        if not self.test_valeur_valide():
            return

        # test si le format des données des lineedit sont bons
        # for widg_str,regex in self.dict_widg_reggex.items():
        #     widg = self.dlg.findChild(QLineEdit, widg_str)
        #     if widg.text() == "NULL":
        #         break
        #     valid = self.is_valid_regex(widg, regex)
        #     if not valid :
        #         QMessageBox.warning(None, "Format invalide", f"Le contenu du champ '{widg.objectName()}' n'est pas valide.")
        #         break

        self.layer.startEditing()

        for ident,valeur_sel in self.dico_attributs_selection.items():
            for champ, valeur in self.dico_attributs_modifie.items():
                # pour les linedit vides
                if valeur == "" or valeur == 0:
                    valeur = "NULL"
                idchamps = self.layer.fields().indexFromName(champ)
                self.layer.changeAttributeValue(ident, idchamps, valeur)

        self.dico_attributs_modifie.clear()
        self.ismodifie = False

        self.actualiserSelection()
        self.afficheMessageBar(
            f"Les modifications ont été effectués sur : {self.layer.selectedFeatureCount()} tronçon(s)")

    def actualiserSelection(self):
        layer = QgsProject.instance().mapLayersByName(LAYER_ROUTE)
        if not layer:
            return
        # remettre le fond par defaut
        self.dlg.lineEditLargeur.setStyleSheet(CUSTOM_WIDGETS[2])
        self.dlg.lineEditRestrHauteur.setStyleSheet(CUSTOM_WIDGETS[2])

        self.dlg.pushButtonValiderTransaction.setEnabled(False)
        self.dlg.pushButtonchepluscourt.setEnabled(False)

        self.listeSelection = self.layer.selectedFeatures()
        self.get_nb_selection()
        self.dlg.labelNbSelection.setText(f"Vous avez sélectionné : <span style='color: red'><b>{self.get_nb_selection()}</b></span> tronçon(s)")


        # gestion de la couleur de selection
        couleur = self.dlg.mColorButton.color()
        self.iface.mapCanvas().setSelectionColor(couleur)

        # sauvegarde des attributs de la selection
        self.set_attributs_selection()

        # initialise un dico avec les attributs commun, à faire APRES set_attributs_selection
        self.set_attributs_commun()

        self.dico_attributs_modifie.clear()

        # initialise juste tous boutons en gras (aucun n'est sélectionné)
        # et met en vert les attributs de la sélection
        self.initbtnclic(self.listBtnTotal)


        if self.get_nb_selection() <1:
            self.activerBoutons(False)
            # vider tous les QLineEdit
            # TODO : ajouter le lineeditlargeur
            for widg_str in LIST_LINEEDIT_RESTR:
                widg = self.dlg.findChild(QLineEdit, widg_str)
                widg.setText("")
        else:
            self.activerBoutons(True)
            self.controleDonnees(self.get_bouton_nature_actif())

        if self.get_nb_selection() == 2:
            self.dlg.pushButtonchepluscourt.setEnabled(True)

        self.dlg.pushButtonActualiseSelection.setEnabled(False)

    # test si le format des données est valide
    def is_valid_regex(self,widget,regex):
        decimal_regex = QRegExp(regex)
        validator = QRegExpValidator(decimal_regex, widget)
        widget.setValidator(validator)
        # Validation du texte actuel dans le widget
        state, _, _ = validator.validate(widget.text(), 0)
        return state == QValidator.Acceptable

    def click_edit(self,widget,champs,event):
        widget.clear()
        # on passe l'edit en rose
        widget.setStyleSheet(CUSTOM_WIDGETS[5])
        self.dlg.pushButtonValiderTransaction.setEnabled(True)
        self.dlg.pushButtonActualiseSelection.setEnabled(True)

    def lineeditchangetext(self,widget,champs,regex):
        # Définir le format du nombre décimal avec un point comme séparateur
        # decimal_regex = QRegExp(r"^\d*\.?\d{1}$")  # Autorise un point décimal, pas de virgule
        # decimal_regex = QRegExp(regex)
        # validator = QRegExpValidator(decimal_regex, widget)
        # widget.setValidator(validator)
        self.is_valid_regex(widget,regex)

        if self.get_nb_selection() == 0:
            return
        self.dico_attributs_modifie[champs] = widget.text()

    def afficher_sens_num(self):
        if self.is_affiche_sens_num:
            self.dlg.pushButtonsensNumerisation.setText("Afficher le sens\n de numérisation")
            suppr_symb_sens_num(self.layer)
            self.is_affiche_sens_num = False
        else:
            self.dlg.pushButtonsensNumerisation.setText("Masquer le sens\n de numérisation")
            add_symb_sens_num(self.layer)
            self.is_affiche_sens_num = True
        self.layer.triggerRepaint()
        self.iface.mapCanvas().refresh()

    def afficheAProposeDe(self):
        self.dlgAProposDe.show()

    def zoom_selection(self):
        self.iface.actionZoomToSelected().trigger()

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ChangeAttributRoute', message)


    def initGui(self):
        pass

    def unload(self):
        pass

    def keyPressEvent(self, event):
        # if event.key() == Qt.Key_Return or event.key() == Qt.Key_Enter:
        #     afficheerreur("touche entrer")
        pass

    def run(self):
        """Run method that performs all the real work"""
        projet = QgsProject.instance()
        if len(projet.mapLayers()) <= 0:
            afficheerreur("Aucun projet chargé")
            return
        # activation du layer route s'il existe
        if not self.set_activeLayerRoute():
            return

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started

        self.dlg = ChangeAttributRouteDialog()
        self.dlg.setWindowTitle(f"{TITRE_INTERFACE}  {VERSION}")

        self.dlgAProposDe = Aproposde()
        self.dlgAProposDe.setWindowFlags(Qt.WindowStaysOnTopHint|Qt.WindowTitleHint | Qt.WindowCloseButtonHint)
        self.dlgAProposDe.pushButtonAffichedoc.clicked.connect(afficheDoc)


        # ******************************
        self.champs_manquant, champs_readonly = test_modele(self.layer)
        self.dlg.pushButton_warning.clicked.connect(lambda: config_modele(self.champs_manquant, champs_readonly))
        # self.dlg.pushButton_warning.hide()
        if len(self.champs_manquant) == 0:
            self.dlg.pushButton_warning.setStyleSheet("qproperty-icon: none;")
        # ******************************

        self.cheminpluscourt = cheminpluscourt(self.iface, self.layer)

        self.dlg.mColorButton.setColor(self.iface.mapCanvas().selectionColor())
        self.dlg.mColorButton.colorChanged.connect(self.colorchange)

        # événement de changement de selection pour actualiser la selection des QCombobox
        self.iface.mapCanvas().selectionChanged.connect(self.actualiserSelection)

        self.dlg.label_2.setStyleSheet(CUSTOM_WIDGETS[3])
        self.dlg.label_3.setStyleSheet(CUSTOM_WIDGETS[3])
        self.dlg.label_4.setStyleSheet(CUSTOM_WIDGETS[3])
        self.dlg.label_5.setStyleSheet(CUSTOM_WIDGETS[3])
        self.dlg.label_6.setStyleSheet(CUSTOM_WIDGETS[3])
        self.dlg.label_7.setStyleSheet(CUSTOM_WIDGETS[3])
        self.dlg.label_9.setStyleSheet(CUSTOM_WIDGETS[3])

        # Bouton change NATURE
        self.dlg.pushButtonRte2Chaussee.clicked.connect(self.torte2chaussee)
        self.dlg.pushButtonRte1Chaussee.clicked.connect(self.torte1chaussee)
        self.dlg.pushButtonEmpierree.clicked.connect(self.toempierree)
        self.dlg.pushButtonChemin.clicked.connect(self.tochemin)
        self.dlg.pushButtonSentier.clicked.connect(self.tosentier)
        self.dlg.pushButtonRondpoint.clicked.connect(self.torondpoint)

        # Bouton change nb voies
        self.dlg.pushButtonVoieSansObjet.clicked.connect(self.setvoieSansObj)
        self.dlg.pushButton1voie.clicked.connect(self.set1voie)
        self.dlg.pushButton2voies.clicked.connect(self.set2voies)
        self.dlg.pushButton3voies.clicked.connect(self.set3voies)

        # événement lineeditlargeur
        self.dlg.lineEditLargeur.mousePressEvent = lambda event :self.click_edit(self.dlg.lineEditLargeur,LARGEUR,event)
        self.dlg.lineEditLargeur.textChanged.connect(lambda:self.lineeditchangetext(self.dlg.lineEditLargeur,LARGEUR,REGEX_LARGEUR))

        # test si le champ NATURE est readonly
        index = self.layer.fields().indexOf(NATURE)
        form_config = self.layer.editFormConfig()
        self.read_only_nature = form_config.readOnly(index)

        # test si le champ NB VOIES est readonly
        index = self.layer.fields().indexOf(NB_VOIES)
        form_config = self.layer.editFormConfig()
        self.read_only_nb_voies = form_config.readOnly(index)

        # test si le champ LARGEUR est readonly
        index = self.layer.fields().indexOf(LARGEUR)
        form_config = self.layer.editFormConfig()
        self.read_only_larg_chaussee = form_config.readOnly(index)

        # test si le champ IMPORTANCE est readonly
        index = self.layer.fields().indexOf(IMPORTANCE)
        form_config = self.layer.editFormConfig()
        self.read_only_importance = form_config.readOnly(index)

        # test si le champ SENS est readonly
        index = self.layer.fields().indexOf(SENS)
        form_config = self.layer.editFormConfig()
        self.read_only_sens_circu = form_config.readOnly(index)

        # test si le champ ACCES est readonly
        index = self.layer.fields().indexOf(ACCES)
        form_config = self.layer.editFormConfig()
        self.read_only_acces_leger = form_config.readOnly(index)

        # test si le champ RESTRICTIONS est readonly
        # si au moins 1 alors tous
        index_restr_hauteur = self.layer.fields().indexOf(RESTRICTION_HAUTEUR)
        index_restr_largeur = self.layer.fields().indexOf(RESTRICTION_LARGEUR)
        index_restr_longueur = self.layer.fields().indexOf(RESTRICTION_LONGUEUR)
        index_restr_poids_essieu = self.layer.fields().indexOf(RESTRICTION_POIDS_ESSIEU)
        index_restr_poids_total = self.layer.fields().indexOf(RESTRICTION_POIDS_TOTAL)
        form_config = self.layer.editFormConfig()
        self.read_only_restr_hauteur = form_config.readOnly(index_restr_hauteur)
        self.read_only_restr_largeur = form_config.readOnly(index_restr_largeur)
        self.read_only_restr_longueur = form_config.readOnly(index_restr_longueur)
        self.read_only_restr_poids_essieu = form_config.readOnly(index_restr_poids_essieu)
        self.read_only_restr_poids_total = form_config.readOnly(index_restr_poids_total)
        if self.read_only_restr_hauteur or self.read_only_restr_largeur or self.read_only_restr_longueur or self.read_only_restr_poids_essieu or self.read_only_restr_poids_total:
            self.read_only_restriction = form_config.readOnly(index)


        self.dlg.pushButtonImportance1.clicked.connect(self.setImportance1)
        self.dlg.pushButtonImportance2.clicked.connect(self.setImportance2)
        self.dlg.pushButtonImportance3.clicked.connect(self.setImportance3)
        self.dlg.pushButtonImportance4.clicked.connect(self.setImportance4)
        self.dlg.pushButtonImportance5.clicked.connect(self.setImportance5)
        self.dlg.pushButtonImportance6.clicked.connect(self.setImportance6)

        # bouton sens
        self.dlg.pushButtonDoubleSens.clicked.connect(self.setDoubleSens)
        self.dlg.pushButtonSensUnique.clicked.connect(self.setSensUnique)
        self.dlg.pushButtonInverserSens.clicked.connect(self.setInverserSens)
        self.dlg.pushButtonSensSansObjet.clicked.connect(self.setSensSansObjet)
        # TODO : pas dans les specs
        # self.dlg.pushButtonSensSansVal.clicked.connect(self.setSensSansValeur)

        # acces
        self.dlg.pushButtonAccesLibre.clicked.connect(self.setAccesLibre)
        self.dlg.pushButtonAccesRestreint.clicked.connect(self.setAccesRestreint)
        self.dlg.pushButtonAccesImpossible.clicked.connect(self.setAccesImpossible)

        # restrictions
        restrictions = [
            (self.dlg.lineEditRestrHauteur,RESTRICTION_HAUTEUR,REGEX_RESTR_HAUTEUR),
            (self.dlg.lineEditRestrLargeur, RESTRICTION_LARGEUR,REGEX_RESTR_LARGEUR),
            (self.dlg.lineEditRestrLongueur, RESTRICTION_LONGUEUR,REGEX_RESTR_LONGUEUR),
            (self.dlg.lineEditRestrPoidsEssieu, RESTRICTION_POIDS_ESSIEU,REGEX_RESTR_POIDS_ESSIEU),
            (self.dlg.lineEditRestrPoidsTotal, RESTRICTION_POIDS_TOTAL,REGEX_RESTR_POIDS_TOTAL),
        ]
        for widget, constante,regex in restrictions:
            widget.mousePressEvent = lambda event, w=widget, c=constante: self.click_edit(w, c, event)
            widget.textChanged.connect(lambda _, w=widget, c=constante,r = regex: self.lineeditchangetext(w, c,r))

        # bouton d'actualisation de la selection
        # pour retrouver l'état initial apres modif, mais avant transaction
        self.dlg.pushButtonActualiseSelection.clicked.connect(self.actualiserSelection)
        self.dlg.pushButtonActualiseSelection.setEnabled(False)

        # bouton a propos de
        self.dlg.pushButtonAide.clicked.connect(self.afficheAProposeDe)

        # bouton chemin le plus court
        self.dlg.pushButtonchepluscourt.clicked.connect(self.runchepluscourt)

        # bouton afficher sens numérisation
        self.dlg.pushButtonsensNumerisation.clicked.connect(self.afficher_sens_num)

        # bouton "zoom sur la sélection"
        self.dlg.pushButtonZoom.clicked.connect(self.zoom_selection)

        # bouton valider la transaction
        self.dlg.pushButtonValiderTransaction.clicked.connect(self.validerLaTransaction)
        self.dlg.pushButtonValiderTransaction.setStyleSheet(CUSTOM_WIDGETS[4])

        self.actualiserSelection()

        # show the dialog
        self.dlg.setParent(self.iface.mainWindow())
        self.dlg.setWindowFlags(Qt.Dialog | Qt.WindowTitleHint | Qt.WindowCloseButtonHint)
        self.dlg.show()

        # Run the dialog event loop
        result = self.dlg.exec_()

        if result == 0:
            suppr_symb_sens_num(self.layer)
            self.layer.triggerRepaint()
            self.is_affiche_sens_num = False
            self.dlgAProposDe.close()